<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="董庆森 秦郑泽">
<meta name="dcterms.date" content="2026-05-20">

<title>LLM Pre-Training Project Report</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../style/icon.avif" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-44ab3f0b617b077ba5b24bd1c24b061e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-0b09eb4da84538f8c2fd112b9812168b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-44ab3f0b617b077ba5b24bd1c24b061e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-E8EJCZTZG1"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-E8EJCZTZG1', { 'anonymize_ip': true});
</script>
<script>
  MathJax = {
    loader: { load: ['[tex]/boldsymbol'] },
    tex: {
      tags: "all",
      inlineMath: [['$','$'], ['\\(','\\)']],
      displayMath: [['$$','$$'], ['\\[','\\]']],
      processEscapes: true,
      processEnvironments: true,
      packages: { '[+]': ['boldsymbol'] }
    }
  };
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;display=swap">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<meta property="og:title" content="LLM Pre-Training Project Report">
<meta property="og:description" content="">
<meta property="og:image" content="https://qsdong-bupt.github.io/posts/Projects/LLM_Pre-Training/assets/LLAMA架构图.png">
<meta property="og:image:alt" content="LLAMA架构图">
<meta property="og:image:height" content="1669">
<meta property="og:image:width" content="691">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/qsdong-bupt"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/qingsen-dong-9aab2520b/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../posts/Blogs/blogs_index.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../posts/Projects/projects_index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-toggle-dark-mode"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#进展情况" id="toc-进展情况" class="nav-link active" data-scroll-target="#进展情况">进展情况</a></li>
  <li><a href="#about-this-project" id="toc-about-this-project" class="nav-link" data-scroll-target="#about-this-project">1 About this Project</a></li>
  <li><a href="#create-a-virtual-environment" id="toc-create-a-virtual-environment" class="nav-link" data-scroll-target="#create-a-virtual-environment">2 Create a Virtual Environment</a>
  <ul class="collapse">
  <li><a href="#虚拟环境设置" id="toc-虚拟环境设置" class="nav-link" data-scroll-target="#虚拟环境设置">2.1 虚拟环境设置</a></li>
  <li><a href="#核心依赖" id="toc-核心依赖" class="nav-link" data-scroll-target="#核心依赖">2.2 核心依赖</a></li>
  </ul></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">3 Dataset</a></li>
  <li><a href="#tokenizer" id="toc-tokenizer" class="nav-link" data-scroll-target="#tokenizer">4 Tokenizer</a>
  <ul class="collapse">
  <li><a href="#bpe-训练" id="toc-bpe-训练" class="nav-link" data-scroll-target="#bpe-训练">4.1 BPE 训练</a></li>
  <li><a href="#tokenizer-类" id="toc-tokenizer-类" class="nav-link" data-scroll-target="#tokenizer-类">4.2 Tokenizer 类</a></li>
  <li><a href="#数据编码" id="toc-数据编码" class="nav-link" data-scroll-target="#数据编码">4.3 数据编码</a></li>
  </ul></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">5 Model</a>
  <ul class="collapse">
  <li><a href="#sec-param-init" id="toc-sec-param-init" class="nav-link" data-scroll-target="#sec-param-init">5.1 参数初始化</a></li>
  <li><a href="#embedding" id="toc-embedding" class="nav-link" data-scroll-target="#embedding">5.2 Embedding</a></li>
  <li><a href="#linear" id="toc-linear" class="nav-link" data-scroll-target="#linear">5.3 Linear</a></li>
  <li><a href="#rmsnorm" id="toc-rmsnorm" class="nav-link" data-scroll-target="#rmsnorm">5.4 RMSNorm</a></li>
  <li><a href="#rope" id="toc-rope" class="nav-link" data-scroll-target="#rope">5.5 RoPE</a></li>
  <li><a href="#softmax" id="toc-softmax" class="nav-link" data-scroll-target="#softmax">5.6 Softmax</a></li>
  <li><a href="#sec-multi-head-attention" id="toc-sec-multi-head-attention" class="nav-link" data-scroll-target="#sec-multi-head-attention">5.7 Multi-Head Attention</a></li>
  <li><a href="#swiglu" id="toc-swiglu" class="nav-link" data-scroll-target="#swiglu">5.8 SwiGLU</a></li>
  <li><a href="#transformer-block" id="toc-transformer-block" class="nav-link" data-scroll-target="#transformer-block">5.9 Transformer Block</a></li>
  <li><a href="#transformermodule" id="toc-transformermodule" class="nav-link" data-scroll-target="#transformermodule">5.10 TransformerModule</a></li>
  </ul></li>
  <li><a href="#pre-training-strategy" id="toc-pre-training-strategy" class="nav-link" data-scroll-target="#pre-training-strategy">6 Pre-training Strategy</a>
  <ul class="collapse">
  <li><a href="#optimizer" id="toc-optimizer" class="nav-link" data-scroll-target="#optimizer">6.1 Optimizer</a></li>
  <li><a href="#crossentropyloss" id="toc-crossentropyloss" class="nav-link" data-scroll-target="#crossentropyloss">6.2 CrossEntropyLoss</a></li>
  <li><a href="#dataloader" id="toc-dataloader" class="nav-link" data-scroll-target="#dataloader">6.3 DataLoader</a></li>
  <li><a href="#lr_cosine_shedule" id="toc-lr_cosine_shedule" class="nav-link" data-scroll-target="#lr_cosine_shedule">6.4 lr_cosine_shedule</a></li>
  <li><a href="#gradient_clip" id="toc-gradient_clip" class="nav-link" data-scroll-target="#gradient_clip">6.5 gradient_clip</a></li>
  </ul></li>
  <li><a href="#pre-training" id="toc-pre-training" class="nav-link" data-scroll-target="#pre-training">7 Pre-Training</a>
  <ul class="collapse">
  <li><a href="#训练脚本" id="toc-训练脚本" class="nav-link" data-scroll-target="#训练脚本">7.1 训练脚本</a></li>
  <li><a href="#检查点与恢复" id="toc-检查点与恢复" class="nav-link" data-scroll-target="#检查点与恢复">7.2 检查点与恢复</a></li>
  <li><a href="#验证评估" id="toc-验证评估" class="nav-link" data-scroll-target="#验证评估">7.3 验证评估</a></li>
  <li><a href="#实验追踪" id="toc-实验追踪" class="nav-link" data-scroll-target="#实验追踪">7.4 实验追踪</a></li>
  <li><a href="#推理" id="toc-推理" class="nav-link" data-scroll-target="#推理">7.5 推理</a></li>
  </ul></li>
  <li><a href="#pre-training-details" id="toc-pre-training-details" class="nav-link" data-scroll-target="#pre-training-details">8 Pre-Training details</a>
  <ul class="collapse">
  <li><a href="#训练配置" id="toc-训练配置" class="nav-link" data-scroll-target="#训练配置">8.1 训练配置</a></li>
  <li><a href="#bpe" id="toc-bpe" class="nav-link" data-scroll-target="#bpe">8.2 BPE</a></li>
  <li><a href="#pre-training-1" id="toc-pre-training-1" class="nav-link" data-scroll-target="#pre-training-1">8.3 pre-training</a></li>
  <li><a href="#结果" id="toc-结果" class="nav-link" data-scroll-target="#结果">8.4 结果</a></li>
  </ul></li>
  <li><a href="#实验" id="toc-实验" class="nav-link" data-scroll-target="#实验">9 实验</a>
  <ul class="collapse">
  <li><a href="#chinchilla-缩放定律" id="toc-chinchilla-缩放定律" class="nav-link" data-scroll-target="#chinchilla-缩放定律">9.1 Chinchilla 缩放定律</a></li>
  <li><a href="#kv_cache" id="toc-kv_cache" class="nav-link" data-scroll-target="#kv_cache">9.2 kv_cache</a></li>
  <li><a href="#flashattention-2" id="toc-flashattention-2" class="nav-link" data-scroll-target="#flashattention-2">9.3 FlashAttention-2</a></li>
  </ul></li>
  <li><a href="#建议" id="toc-建议" class="nav-link" data-scroll-target="#建议">10 建议</a>
  <ul class="collapse">
  <li><a href="#优先阅读代码而非训练实操" id="toc-优先阅读代码而非训练实操" class="nav-link" data-scroll-target="#优先阅读代码而非训练实操">10.1 优先阅读代码而非训练实操</a></li>
  <li><a href="#代码测试非常重要" id="toc-代码测试非常重要" class="nav-link" data-scroll-target="#代码测试非常重要">10.2 代码测试非常重要</a></li>
  <li><a href="#一定要看数据集内容" id="toc-一定要看数据集内容" class="nav-link" data-scroll-target="#一定要看数据集内容">10.3 一定要看数据集内容！！！</a></li>
  <li><a href="#参数初始化对本实验影响不大" id="toc-参数初始化对本实验影响不大" class="nav-link" data-scroll-target="#参数初始化对本实验影响不大">10.4 参数初始化对本实验影响不大</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="报告.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li><li><a href="报告.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">LLM Pre-Training Project Report</h1>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>董庆森 秦郑泽 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="进展情况" class="level2">
<h2 class="anchored" data-anchor-id="进展情况">进展情况</h2>
<p>项目名称：<strong>从零构建LLM</strong>。</p>
<p>项目分为以下四个模块：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>模块</th>
<th>内容</th>
<th>状态</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>模块一</td>
<td>基础模块搭建与预训练</td>
<td>已完成</td>
</tr>
<tr class="even">
<td>模块二</td>
<td>后训练（SFT + RL对齐）</td>
<td>待完成</td>
</tr>
<tr class="odd">
<td>模块三</td>
<td>系统优化（训练优化 + 推理优化）</td>
<td>已完成</td>
</tr>
<tr class="even">
<td>模块四</td>
<td>训练数据工程</td>
<td>待完成</td>
</tr>
</tbody>
</table>
<p>本实验报告是用qmd文件编写，建议查看网页版（报告.html）以获得更好的阅读体验。</p>
<p>地址：<a href="https://qsdong-bupt.github.io/posts/Projects/LLM_Pre-Training/">报告</a></p>
</section>
<section id="about-this-project" class="level2">
<h2 class="anchored" data-anchor-id="about-this-project">1 About this Project</h2>
<p>本项目从头实现了一个基于解码器（decoder-only）架构的因果 Transformer 语言模型，整体设计参考 LLaMA 模型的架构<a href="https://arxiv.org/abs/2302.13971">LLaMA (2023)</a> 。 和 GPT 系列一样，LLaMA 模型也是 Decoder-only 架构，但结合前人的工作做了一些改进，比如：</p>
<ol type="1">
<li><strong>Pre-normalization</strong> [GPT3]. 为了提高训练稳定性，LLaMA 对每个 transformer 子层的输入进行归一化，使用 <strong>RMSNorm</strong> 归一化函数，Pre-normalization 由Zhang和Sennrich（2019）引入。使用 <strong>RMSNorm</strong> 的好处是不用计算样本的均值，速度提升了 40%</li>
<li><strong>FFN_SWiGLU</strong> [PaLM]。结构上使用门控线性单元，且为了保持 FFN 层参数数量不变，将隐藏单元的数量调整为 <span class="math inline">\(\frac{2}{3}4d\)</span> 而不是 PaLM 论文中的 <span class="math inline">\(4d\)</span>，同时将 ReLU 替换为 <strong>SiLU</strong> [Shazeer,2020] 激活，引入以提高性能。</li>
<li><strong>Rotary Embeddings</strong> [GPTNeo]。模型的输入不再使用 positional embeddings，而是在网络的每一层添加了 positional embeddings（<strong>RoPE</strong>），RoPE 方法由Su等人（2021）引入。</li>
</ol>
<p>完整的模型结构图如下图所示: <img src="assets/LLAMA架构图.png" class="img-fluid" alt="LLAMA架构图"></p>
<p>项目的核心特点包括：</p>
<ul>
<li><strong>全组件自定义实现</strong>：不依赖 PyTorch 内置的 <code>nn.Linear</code>、<code>nn.Embedding</code> 等高层模块，所有组件（线性层、嵌入层、归一化层、注意力机制、前馈网络等）均从底层手动实现。</li>
<li><strong>现代化 Transformer 架构</strong>：
<ul>
<li><strong>RMSNorm</strong>：均方根层归一化，替代传统的 LayerNorm</li>
<li><strong>RoPE</strong>（Rotary Position Embedding）：旋转位置编码</li>
<li><strong>SwiGLU</strong>：使用 SiLU 激活函数的门控前馈网络</li>
<li><strong>Pre-Norm</strong>：在注意力/FFN 之前进行归一化的残差连接结构</li>
</ul></li>
<li><strong>BPE 分词器</strong>：基于 GPT-2 风格的 Byte-Pair Encoding 算法，支持自定义词表大小</li>
<li><strong>完整训练流程</strong>：包含 AdamW 优化器、余弦学习率调度、梯度裁剪、梯度累积等训练基础设施</li>
</ul>
<p>项目代码位于 <a href="basics/">basics/</a> 目录下，按功能模块组织到 <code>model/</code>、<code>train/</code>、<code>tokenizer/</code>、<code>inference/</code> 等子目录中。</p>
</section>
<section id="create-a-virtual-environment" class="level2">
<h2 class="anchored" data-anchor-id="create-a-virtual-environment">2 Create a Virtual Environment</h2>
<section id="虚拟环境设置" class="level3">
<h3 class="anchored" data-anchor-id="虚拟环境设置">2.1 虚拟环境设置</h3>
<p>项目使用 Python 虚拟环境管理依赖，虚拟环境位于项目根目录下的 <a href=".venv/"><code>.venv/</code></a> 文件夹中。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建虚拟环境</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-m</span> venv .venv</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 激活虚拟环境 (Windows PowerShell)</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">.</span><span class="dt">\.</span>venv<span class="dt">\S</span>cripts<span class="dt">\A</span>ctivate.ps1</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 激活虚拟环境 (Windows CMD)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="ex">.venv\Scripts\activate.bat</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 激活虚拟环境 (Linux / macOS)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="核心依赖" class="level3">
<h3 class="anchored" data-anchor-id="核心依赖">2.2 核心依赖</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>依赖包</th>
<th>版本</th>
<th>用途</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>torch</code></td>
<td>≥ 2.0</td>
<td>深度学习框架</td>
</tr>
<tr class="even">
<td><code>numpy</code></td>
<td>≥ 1.24</td>
<td>数值计算</td>
</tr>
<tr class="odd">
<td><code>wandb</code></td>
<td>latest</td>
<td>实验跟踪与日志记录</td>
</tr>
<tr class="even">
<td><code>tqdm</code></td>
<td>latest</td>
<td>进度条显示</td>
</tr>
<tr class="odd">
<td><code>regex</code></td>
<td>latest</td>
<td>高级正则表达式（分词器）</td>
</tr>
<tr class="even">
<td><code>pickle</code></td>
<td>内置</td>
<td>词汇表和合并规则的序列化</td>
</tr>
</tbody>
</table>
<p>安装命令：</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install torch numpy wandb tqdm regex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">3 Dataset</h2>
<ul>
<li><strong>语料</strong>：OpenWebText（OWT），共 <strong>1,458,472,895 个 token</strong>（约 14.58 亿）</li>
<li><strong>预处理</strong>：原始文本 → BPE 编码 → token ID 序列 → 保存为 PyTorch 张量</li>
<li><strong>文件</strong>：
<ul>
<li><a href="basics/data/owt_32768_ids_train.pkl">basics/data/owt_32768_ids_train.pkl</a> — 训练集</li>
<li><a href="basics/data/owt_32768_ids_valid.pkl">basics/data/owt_32768_ids_valid.pkl</a> — 验证集</li>
</ul></li>
</ul>
</section>
<section id="tokenizer" class="level2">
<h2 class="anchored" data-anchor-id="tokenizer">4 Tokenizer</h2>
<section id="bpe-训练" class="level3">
<h3 class="anchored" data-anchor-id="bpe-训练">4.1 BPE 训练</h3>
<p><strong>文件：</strong> <a href="basics/tokenizer/train_bpe.py">basics/tokenizer/train_bpe.py</a></p>
<p>BPE（Byte-Pair Encoding）分词器训练流程：</p>
<ol type="1">
<li><strong>基础词汇表</strong>：以 256 个单字节（0-255）为基础，加上特殊标记（如 <code>&lt;|endoftext|&gt;</code>）</li>
<li><strong>预分词（Pre-tokenization）</strong>：使用 GPT-2 风格的正则表达式进行预分词：</li>
</ol>
<pre><code>'(?:[sdmt]|ll|ve|re)| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+</code></pre>
<p>该正则保留英文缩写、字母序列、数字序列、标点符号和空白字符。</p>
<ol start="3" type="1">
<li><strong>训练循环</strong>：
<ul>
<li>统计所有相邻 token 对的频率（<code>pair_counts</code>）</li>
<li>维护反向索引 <code>pair_to_tokens</code>，实现 <span class="math inline">\(O(1)\)</span> 查找受影响的 token</li>
<li>每次选择频率最高的 token 对进行合并</li>
<li>平局时按字节序选择最大的对</li>
<li>更新受影响的 token 和 pair 计数</li>
<li>重复直到词表达到目标大小</li>
</ul></li>
<li><strong>词表规模</strong>：项目中训练的词表大小为 32768</li>
</ol>
<p>核心合并循环：</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 初始化: vocab[0..255] = 单字节; pair_counts 统计所有相邻对频率</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># pair_to_tokens: 反向索引，O(1) 查找受影响的 token</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> <span class="bu">len</span>(vocab) <span class="op">&lt;</span> vocab_size:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> pair_counts:</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 选频率最高的 pair，平局选字节序最大</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    max_count <span class="op">=</span> <span class="bu">max</span>(pair_counts.values())</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    candidates <span class="op">=</span> [k <span class="cf">for</span> k, v <span class="kw">in</span> pair_counts.items() <span class="cf">if</span> v <span class="op">==</span> max_count]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    best_pair <span class="op">=</span> <span class="bu">max</span>(candidates)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    merges.append(best_pair)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    new_token_bytes <span class="op">=</span> best_pair[<span class="dv">0</span>] <span class="op">+</span> best_pair[<span class="dv">1</span>]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    vocab[current_next_id] <span class="op">=</span> new_token_bytes</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    current_next_id <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># O(1) 获取受影响 tokens，更新 pair_counts 和 token_frequency_table</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    affected_tokens <span class="op">=</span> <span class="bu">list</span>(pair_to_tokens.get(best_pair, []))</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> token <span class="kw">in</span> affected_tokens:</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        freq <span class="op">=</span> token_frequency_table.get(token, <span class="dv">0</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> freq <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 从 pair_counts 中移除旧 token 的贡献</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(token) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> (token[i], token[i<span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>            pair_counts[p] <span class="op">-=</span> freq</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>            pair_to_tokens[p].discard(token)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> pair_counts[p] <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>                <span class="kw">del</span> pair_counts[p]</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 合并 best_pair 后重新添加</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>        new_token_seq <span class="op">=</span> merge_token_sequence(token, best_pair, new_token_bytes)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(new_token_seq) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> (new_token_seq[i], new_token_seq[i<span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>            pair_counts[p] <span class="op">+=</span> freq</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>            pair_to_tokens[p].add(new_token_seq)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        <span class="kw">del</span> token_frequency_table[token]</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>        token_frequency_table[new_token_seq] <span class="op">+=</span> freq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="tokenizer-类" class="level3">
<h3 class="anchored" data-anchor-id="tokenizer-类">4.2 Tokenizer 类</h3>
<p><strong>文件：</strong> <a href="basics/tokenizer/tokenizer.py">basics/tokenizer/tokenizer.py</a></p>
<ul>
<li><strong>encode(text)</strong>：正则分割 → 逐词 BPE 合并 → token ID 查找</li>
<li><strong>decode(ids)</strong>：ID → bytes 拼接 → UTF-8 解码</li>
<li><strong>BPE 缓存</strong>：对已编码的词进行缓存，避免重复计算</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Tokenizer:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _get_bpe_merges(<span class="va">self</span>, piece: <span class="bu">bytes</span>) <span class="op">-&gt;</span> List[<span class="bu">bytes</span>]:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        parts <span class="op">=</span> [<span class="bu">bytes</span>([b]) <span class="cf">for</span> b <span class="kw">in</span> piece]    <span class="co"># 单字节列表</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">while</span> <span class="bu">len</span>(parts) <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>            pairs <span class="op">=</span> <span class="bu">set</span>()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(parts) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                pair <span class="op">=</span> (parts[i], parts[i<span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> pair <span class="kw">in</span> <span class="va">self</span>.merges_set:</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                    pairs.add(pair)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="kw">not</span> pairs:</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                <span class="cf">break</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            <span class="co"># 选择 merges 优先级最高（最早被学习）的 pair</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            best_pair <span class="op">=</span> <span class="bu">min</span>(pairs, key<span class="op">=</span><span class="kw">lambda</span> p: <span class="va">self</span>.merges_priority_map[p])</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>            <span class="co"># 合并 best_pair</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>            new_parts <span class="op">=</span> []</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>            i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">while</span> i <span class="op">&lt;</span> <span class="bu">len</span>(parts):</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> i <span class="op">&lt;</span> <span class="bu">len</span>(parts)<span class="op">-</span><span class="dv">1</span> <span class="kw">and</span> (parts[i], parts[i<span class="op">+</span><span class="dv">1</span>]) <span class="op">==</span> best_pair:</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>                    new_parts.append(parts[i] <span class="op">+</span> parts[i<span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>                    i <span class="op">+=</span> <span class="dv">2</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>                <span class="cf">else</span>:</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>                    new_parts.append(parts[i])</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>                    i <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>            parts <span class="op">=</span> new_parts</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> parts</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> encode(<span class="va">self</span>, text: <span class="bu">str</span>) <span class="op">-&gt;</span> List[<span class="bu">int</span>]:</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> text:</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> []</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        chunks <span class="op">=</span> regex.split(<span class="st">'|'</span>.join(<span class="bu">map</span>(regex.escape, <span class="va">self</span>.special_tokens)), text)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>        final_ids <span class="op">=</span> []</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>        bpe_cache <span class="op">=</span> {}</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> chunk <span class="kw">in</span> chunks:</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="kw">not</span> chunk:</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>                <span class="cf">continue</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> chunk <span class="kw">in</span> <span class="va">self</span>.special_tokens:</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>                final_ids.append(<span class="va">self</span>.bytes_to_id[chunk.encode(<span class="st">'utf-8'</span>)])</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> word <span class="kw">in</span> regex.findall(PAT, chunk):</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">if</span> word <span class="kw">not</span> <span class="kw">in</span> bpe_cache:</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>                        bpe_cache[word] <span class="op">=</span> <span class="va">self</span>._get_bpe_merges(word.encode(<span class="st">'utf-8'</span>))</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> b <span class="kw">in</span> bpe_cache[word]:</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>                        final_ids.append(<span class="va">self</span>.bytes_to_id[b])</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> final_ids</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> decode(<span class="va">self</span>, token_ids: List[<span class="bu">int</span>]) <span class="op">-&gt;</span> <span class="bu">str</span>:</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>        all_bytes <span class="op">=</span> <span class="st">b''</span>.join(<span class="va">self</span>.vocab[<span class="bu">id</span>] <span class="cf">for</span> <span class="bu">id</span> <span class="kw">in</span> token_ids)</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> all_bytes.decode(<span class="st">'utf-8'</span>, errors<span class="op">=</span><span class="st">'replace'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="数据编码" class="level3">
<h3 class="anchored" data-anchor-id="数据编码">4.3 数据编码</h3>
<p><strong>文件：</strong> <a href="basics/tokenizer/encode_data.py">basics/tokenizer/encode_data.py</a></p>
<p>将原始文本文件编码为 token ID 张量，保存为 <code>.pkl</code> 文件供训练使用。</p>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">5 Model</h2>
<p>模型整体架构采用 decoder-only Transformer（类似 Llama），由嵌入层、多个 Transformer 块、最终 RMSNorm 和 LM 头组成。以下逐一介绍各组件。</p>
<section id="sec-param-init" class="level3">
<h3 class="anchored" data-anchor-id="sec-param-init">5.1 参数初始化</h3>
<p>我们训练神经网络的目的是为了找到一组参数，使得模型在训练数据上的表 现最好。但是，如果初始参数设置不当，可能会导致模型无法收敛或者收敛到局 部最优解甚至出现梯度爆炸、梯度消失等问题。</p>
<p>最常见的两种参数初始化方法：<strong>Xavier 初始化</strong>和 <strong>He 初始化</strong>。</p>
<p><strong>Xavier 初始化 (Glorot Initialization)</strong></p>
<p>Xavier 初始化由 Xavier Glorot 和 Yoshua Bengio 在 2010 年提出。 它的核心思想是保持每一层激活值的方差和反向传播时梯度的方差，在前向和反向传播中保持不变。 Xavier 初始化适用于 <strong>Sigmoid、Tanh</strong> 等对称激活函数。</p>
<p>Xavier 初始化通常有两种分布形式：</p>
<ul>
<li><p><strong>均匀分布 (Uniform)</strong> 权重从均匀分布 <span class="math inline">\(U[-r, r]\)</span> 中采样，其中： <span class="math display">\[
r = \sqrt{\frac{6}{\text{fan}_{in} + \text{fan}_{out}}}
\]</span> 均匀分布的方差为 <span class="math inline">\(\frac{(b-a)^2}{12} = \frac{r^2}{3}\)</span>。 这里的 <span class="math inline">\(\text{fan}_{in}\)</span> 是一层网络输入神经元数量，<span class="math inline">\(\text{fan}_{out}\)</span> 是输出神经元数量。</p></li>
<li><p><strong>正态分布 (Normal)</strong> 权重从均值为 0、标准差为 <span class="math inline">\(\sigma\)</span> 的正态分布中采样，其中： <span class="math display">\[
\sigma = \sqrt{\frac{2}{\text{fan}_{in} + \text{fan}_{out}}}
\]</span> 这是由于每经过一层，权重的方差就会变成原来的 <span class="math inline">\(\frac{1}{\text{fan}}\)</span>，其中 <span class="math inline">\(\text{fan}\)</span> 表示这一层的神经元数量。</p></li>
</ul>
<p>工作原理简述： 通过同时考虑输入和输出神经元的数量，Xavier 初始化试图在层与层之间找到一个平衡点，使得信号的方差既不会在传播中衰减，也不会无限放大。</p>
<p><strong>He 初始化 (Kaiming Initialization)</strong></p>
<p>He 初始化由 Kaiming He（何凯明，残差网络也是他提出的）在 2015 年提出。 针对 Xavier 初始化在 <strong>ReLU 激活函数</strong>上效果不佳的问题，He 初始化专门适配于 ReLU 系列激活函数。</p>
<p>ReLU 函数 <span class="math inline">\(f(x) = \max(0, x)\)</span> 的特性是，它会将所有负输入都变为 0。 这破坏了 Xavier 初始化所依赖的“激活函数关于原点对称”的假设，并导致大约一半的神经元输出为 0，从而改变了输出的方差。</p>
<p>He 初始化考虑到 ReLU 会将一半的输入置为零，这会使得输出方差减半。 为了补偿这一点，He 初始化在计算方差时引入了一个因子 2，其他思路与 Xavier 初始化一致。</p>
<ul>
<li><p><strong>均匀分布 (Uniform)</strong> 权重从均匀分布 <span class="math inline">\(U[-r, r]\)</span> 中采样，其中： <span class="math display">\[
r = \sqrt{\frac{6}{\text{fan}_{in}}}
\]</span></p></li>
<li><p><strong>正态分布 (Normal)</strong> 权重从均值为 0、标准差为 <span class="math inline">\(\sigma\)</span> 的正态分布中采样，其中： <span class="math display">\[
\sigma = \sqrt{\frac{2}{\text{fan}_{in}}}
\]</span></p></li>
</ul>
<p>之所以 Kaiming 初始化只考虑 <span class="math inline">\(\text{fan}_{in}\)</span>，是因为它更注重前向传播，对反向传播的影响考虑较少。</p>
<p><strong>实验中参数初始化标准</strong></p>
<ul>
<li><strong>词嵌入权重</strong>：<span class="math inline">\(\mathcal{N}(\mu = 0, \sigma^2 = 0.02^2)\)</span>，范围限制在 <span class="math inline">\(\pm 3\sigma\)</span> 以内。</li>
<li><strong>线性层权重</strong>：<span class="math inline">\(\mathcal{N}(\mu = 0, \sigma^2 = 0.02^2)\)</span>，范围限制在 <span class="math inline">\(\pm 3\sigma\)</span> 以内。</li>
<li><strong>RMSNorm 权重</strong>：<span class="math inline">\(1\)</span></li>
</ul>
</section>
<section id="embedding" class="level3">
<h3 class="anchored" data-anchor-id="embedding">5.2 Embedding</h3>
<p><strong>文件：</strong> <a href="basics/model/embedding.py">basics/model/embedding.py</a></p>
<p>嵌入层将 token ID 映射为稠密向量。本实现使用自定义的 <code>nn.Parameter</code> 矩阵，而非 PyTorch 内置的 <code>nn.Embedding</code>：</p>
<ul>
<li><strong>权重矩阵</strong>：形状为 <code>[vocab_size, d_model]</code> 的可训练参数</li>
<li><strong>初始化</strong>：使用截断正态分布（Truncated Normal），标准差 <span class="math inline">\(\sigma = 0.02\)</span>，截断范围 <span class="math inline">\([-3\sigma, 3\sigma]\)</span></li>
<li><strong>前向传播</strong>：通过索引查找 <code>embedding_matrix[token_ids]</code> 获取嵌入向量</li>
</ul>
<p><strong>为什么选择截断正态分布？</strong> 标准正态分布理论上可以产生任意大的值（如 <span class="math inline">\(+4\sigma\)</span> 甚至 <span class="math inline">\(+5\sigma\)</span>），这些离群值会导致少数 token 的嵌入向量初始范数过大，在注意力点积中形成异常大的权重，扰乱前几轮训练的梯度流。截断到 <span class="math inline">\([-3\sigma, 3\sigma]\)</span> 后，正态分布中 99.7% 的样本被完整保留，同时每个维度的绝对值永远不会超过 <span class="math inline">\(3\sigma = 0.06\)</span>——相当于给初始嵌入加了硬上限，训练初期的数值更加稳定。<span class="math inline">\(\sigma=0.02\)</span> 是 GPT 系列（GPT-2/3）沿用的经验值。选用这么小的初始化的另一个重要原因是：嵌入向量和输出层的权重都很小时，模型初始输出的 logits 接近零，softmax 近似均匀分布，交叉熵损失自然从 <span class="math inline">\(\log(\text{vocab\_size})\)</span> 附近开始（本项目词表大小为 32768，对应约为 <span class="math inline">\(\ln(32768) \approx 10.4\)</span>）。</p>
<p>由于 <code>erfinv</code> 不支持 <code>bfloat16</code>，初始化在 <code>float32</code> 精度下完成后再转换为目标精度。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> EmbeddingModule(nn.Module):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, vocab_size, d_model, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span>torch.bfloat16):</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        temp_matrix <span class="op">=</span> torch.empty(vocab_size, d_model, device<span class="op">=</span>device, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        std <span class="op">=</span> <span class="fl">0.02</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        torch.nn.init.trunc_normal_(temp_matrix, std<span class="op">=</span>std, a<span class="op">=-</span><span class="dv">3</span><span class="op">*</span>std, b<span class="op">=</span><span class="dv">3</span><span class="op">*</span>std)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.embedding_matrix <span class="op">=</span> nn.Parameter(temp_matrix.to(dtype))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, token_ids: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.embedding_matrix[token_ids]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="linear" class="level3">
<h3 class="anchored" data-anchor-id="linear">5.3 Linear</h3>
<p><strong>文件：</strong> <a href="basics/model/Linear.py">basics/model/Linear.py</a></p>
<p>自定义线性层替代 PyTorch 的 <code>nn.Linear</code>：</p>
<ul>
<li>前向传播：<span class="math inline">\(y = xW^T + b\)</span></li>
<li>权重初始化：正态分布，均值 0，标准差 <span class="math inline">\(\sigma = 0.02\)</span></li>
<li>偏置初始化：均匀分布 <span class="math inline">\(\mathcal{U}(-\frac{1}{\sqrt{d_{in}}}, \frac{1}{\sqrt{d_{in}}})\)</span></li>
<li>支持可选的偏置（<code>bias=True/False</code>）</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Linear(nn.Module):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, in_features, out_features, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span><span class="va">None</span>, bias<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.weight <span class="op">=</span> nn.Parameter(torch.empty(out_features, in_features, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.bias <span class="op">=</span> nn.Parameter(torch.empty(out_features, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)) <span class="cf">if</span> bias <span class="cf">else</span> <span class="va">None</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>._init_weight()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _init_weight(<span class="va">self</span>):</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        std <span class="op">=</span> <span class="fl">0.02</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>            temp_weight <span class="op">=</span> <span class="va">self</span>.weight.to(torch.float32)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            torch.nn.init.normal_(temp_weight, mean<span class="op">=</span><span class="fl">0.0</span>, std<span class="op">=</span>std)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="va">self</span>.weight.copy_(temp_weight.to(orig_dtype))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.bias <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>            fan_in <span class="op">=</span> <span class="va">self</span>.weight.shape[<span class="dv">1</span>]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>            bound <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (fan_in <span class="op">**</span> <span class="fl">0.5</span>) <span class="cf">if</span> fan_in <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="dv">0</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            torch.nn.init.uniform_(<span class="va">self</span>.bias, <span class="op">-</span>bound, bound)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        o <span class="op">=</span> x <span class="op">@</span> <span class="va">self</span>.weight.T</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="va">self</span>.bias <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>            o <span class="op">=</span> o <span class="op">+</span> <span class="va">self</span>.bias</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> o</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="rmsnorm" class="level3">
<h3 class="anchored" data-anchor-id="rmsnorm">5.4 RMSNorm</h3>
<p><strong>文件：</strong> <a href="basics/model/RMSnorm.py">basics/model/RMSnorm.py</a></p>
<section id="pre-norm-vs-post-norm" class="level4">
<h4 class="anchored" data-anchor-id="pre-norm-vs-post-norm">Pre-Norm vs Post-Norm</h4>
<p>在 Transformer 中，归一化层（LayerNorm / RMSNorm）与残差连接的相对位置有两种范式，这对训练稳定性的影响至关重要。</p>
<p><strong>Post-Norm（后归一化）</strong> 是原始 Transformer（Vaswani et al., 2017）的设计——先做残差加法，再归一化：</p>
<p><span class="math display">\[\mathbf{x}_{l+1} = \text{LayerNorm}\big(\mathbf{x}_l + F_l(\mathbf{x}_l)\big)\]</span></p>
<p>其中 <span class="math inline">\(F_l\)</span> 是子层函数（注意力或 FFN），归一化包裹了残差连接。在一个完整的 Transformer Block 中：</p>
<p><span class="math display">\[\begin{aligned}
\mathbf{x}_{l+\frac{1}{2}} &amp;= \text{LN}\big(\mathbf{x}_l + \text{MHA}(\mathbf{x}_l)\big) \\
\mathbf{x}_{l+1} &amp;= \text{LN}\big(\mathbf{x}_{l+\frac{1}{2}} + \text{FFN}(\mathbf{x}_{l+\frac{1}{2}})\big)
\end{aligned}\]</span></p>
<p><strong>Pre-Norm（前归一化）</strong> 是现代 LLM（GPT-2/3/4、LLaMA、PaLM）的标准做法——先归一化，再做子层计算，最后残差加法：</p>
<p><span class="math display">\[\mathbf{x}_{l+1} = \mathbf{x}_l + F_l\big(\text{LayerNorm}(\mathbf{x}_l)\big)\]</span></p>
<p><span class="math display">\[\begin{aligned}
\mathbf{x}_{l+\frac{1}{2}} &amp;= \mathbf{x}_l + \text{MHA}\big(\text{LN}(\mathbf{x}_l)\big) \\
\mathbf{x}_{l+1} &amp;= \mathbf{x}_{l+\frac{1}{2}} + \text{FFN}\big(\text{LN}(\mathbf{x}_{l+\frac{1}{2}})\big)
\end{aligned}\]</span></p>
<p>两种范式的根本区别在于<strong>残差路径是否经过归一化</strong>：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 35%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>对比维度</th>
<th>Post-Norm</th>
<th>Pre-Norm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>残差路径</td>
<td>经过 LN，非恒等映射</td>
<td>恒等映射（<span class="math inline">\(\mathbf{I}\)</span>），直通</td>
</tr>
<tr class="even">
<td>反向传播梯度</td>
<td>通过 LN Jacobian，逐层指数衰减</td>
<td>恒等项保证梯度下界 ≥ 1</td>
</tr>
<tr class="odd">
<td>深层训练</td>
<td>超过 ~20 层梯度消失</td>
<td>GPT-3 96 层、PaLM 118 层均稳定</td>
</tr>
<tr class="even">
<td>学习率预热（warmup）</td>
<td><strong>必需</strong>，否则发散</td>
<td><strong>不需要</strong>，从零步即可正常训练</td>
</tr>
<tr class="odd">
<td>各层贡献</td>
<td>均衡，每层输出归一化</td>
<td>后期层贡献递减（depth dilution）</td>
</tr>
<tr class="even">
<td>历史模型</td>
<td>Transformer、BERT</td>
<td>GPT-2→4、LLaMA、PaLM、Chinchilla</td>
</tr>
</tbody>
</table>
<p><strong>Pre-Norm 为什么更稳定？</strong> 从反向传播的梯度看，Post-Norm 每一层的梯度都必须通过 LayerNorm 的 Jacobian 矩阵（其特征值 &lt; 1），<span class="math inline">\(L\)</span> 层连乘后梯度呈指数衰减 <span class="math inline">\(\sim O(1/2^{L/2})\)</span>，深层网络早期层几乎收不到梯度。而 Pre-Norm 的残差路径是恒等映射 <span class="math inline">\(\mathbf{I}\)</span>，梯度始终保底为 1：</p>
<p><span class="math display">\[\nabla_{\theta_i}\mathcal{L} = \frac{\partial\mathcal{L}}{\partial \mathbf{x}_N} \left[\prod (\mathbf{I} + \mathbf{J}_{F_j} \cdot \mathbf{J}_{\text{LN}_j})\right] \frac{\partial \mathbf{x}_{i+1}}{\partial\theta_i}\]</span></p>
<p>即使子层梯度消失，恒等项 <span class="math inline">\(\mathbf{I}\)</span> 仍保证信号无损回传。Xiong et al.&nbsp;(ICML 2020) 用平均场理论证明：Post-LN 在初始化时刻靠近输出层的参数的梯度期望呈 <span class="math inline">\(\Theta(c_d^{N-i})\)</span> 增长（<span class="math inline">\(c_d &gt; 1\)</span>），即输出层处梯度爆炸；而 Pre-LN 所有层的梯度均被 <span class="math inline">\(\Theta(1)\)</span> 界限，与深度无关。</p>
<p>本项目采用 <strong>Pre-Norm + RMSNorm</strong> 的组合——Pre-Norm 保证深层训练的梯度稳定性，RMSNorm 提供比 LayerNorm 更高效的计算。</p>
</section>
<section id="rmsnorm-本身" class="level4">
<h4 class="anchored" data-anchor-id="rmsnorm-本身">RMSNorm 本身</h4>
<p>RMSNorm 是 LayerNorm 的简化版本，去除了均值中心化，只保留缩放：</p>
<p><span class="math display">\[\text{RMSNorm}(x) = \frac{x}{\sqrt{\text{mean}(x^2) + \epsilon}} \cdot \gamma\]</span></p>
<ul>
<li>在 <code>float32</code> 精度下计算以提高数值稳定性，计算完成后转回原始精度</li>
<li>可学习的缩放参数 <span class="math inline">\(\gamma\)</span>（<code>weight</code>），初始化为全 1</li>
</ul>
<p>移除均值计算可以带来以下好处：</p>
<ul>
<li><p><strong>计算效率更高</strong>：计算均值需要对所有元素求和再除以维度，这本身是一个 <span class="math inline">\(O(D)\)</span> 的操作。移除这一步可以减少计算量，尤其是在硬件层面上可能更高效。</p></li>
<li><p><strong>内存占用更少</strong>：不计算和存储均值，也不需要 <span class="math inline">\(\beta\)</span> 参数。</p></li>
<li><p><strong>简化模型</strong>：参数更少，模型更简洁。</p></li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> RMSnorm(nn.Module):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d_model, eps<span class="op">=</span><span class="fl">1e-5</span>, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.eps <span class="op">=</span> eps</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.weight <span class="op">=</span> nn.Parameter(torch.ones(d_model, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _rms(<span class="va">self</span>, x):</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.weight <span class="op">*</span> (x <span class="op">/</span> torch.sqrt(torch.mean(x<span class="op">**</span><span class="dv">2</span>, dim<span class="op">=-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>) <span class="op">+</span> <span class="va">self</span>.eps))</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>        input_dtype <span class="op">=</span> x.dtype</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x.to(torch.float32)         <span class="co"># 高精度计算</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>        x_normed <span class="op">=</span> <span class="va">self</span>._rms(x)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x_normed.to(input_dtype)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="rope" class="level3">
<h3 class="anchored" data-anchor-id="rope">5.5 RoPE</h3>
<p><strong>文件：</strong> <a href="basics/model/rope.py">basics/model/rope.py</a></p>
<section id="为什么需要位置编码" class="level4">
<h4 class="anchored" data-anchor-id="为什么需要位置编码">为什么需要位置编码？</h4>
<p>Self-Attention 的公式为：</p>
<p><span class="math display">\[\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V\]</span></p>
<p>其中 <span class="math inline">\(QK^T\)</span> 计算的是 token 之间的相似度权重。这个运算本质上是<strong>位置无关的</strong>——对 “我写代码” 和 “代码写我”，Attention 看到的 token 间权重关系完全相同。显然这不符合自然语言的性质：顺序不同，语义完全不同。因此需要<strong>位置编码（Position Encoding）</strong> 告诉模型每个 token 在序列中的位置。</p>
<p>位置编码分为两类：</p>
<ul>
<li><strong>绝对位置编码</strong>：给每个位置一个固定的向量标识（如原始 Transformer 的正弦位置编码），位置 0 用 <span class="math inline">\(\text{PE}_0\)</span>，位置 1 用 <span class="math inline">\(\text{PE}_1\)</span>，以此类推。</li>
<li><strong>相对位置编码</strong>：关注的是两个 token 之间的<strong>距离</strong>，而非绝对位置。例如 “我” 和 “代码” 在 “今天我写代码” 和 “我写代码” 中的相对距离都是 2，关系应当一致。</li>
</ul>
<p>RoPE 的巧妙之处在于：它用<strong>旋转操作</strong>注入位置信息，使得 Attention 内积天然只依赖相对位置。</p>
</section>
<section id="核心思想从-2d-旋转出发" class="level4">
<h4 class="anchored" data-anchor-id="核心思想从-2d-旋转出发">核心思想：从 2D 旋转出发</h4>
<p>在 2D 平面中，向量 <span class="math inline">\((x, y)\)</span> 逆时针旋转角度 <span class="math inline">\(\theta\)</span> 得到：</p>
<p><span class="math display">\[\begin{pmatrix} x' \\ y' \end{pmatrix} = \begin{pmatrix} \cos\theta &amp; -\sin\theta \\ \sin\theta &amp; \cos\theta \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix}\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/2D_Rotation_Demo.png" class="img-fluid figure-img"></p>
<figcaption>2D Rotation Demo</figcaption>
</figure>
</div>
<p>RoPE 的目标是找到一个位置编码函数 <span class="math inline">\(f\)</span>，使得 <span class="math inline">\(Q\)</span> 和 <span class="math inline">\(K\)</span> 的内积仅依赖相对位置 <span class="math inline">\((m - n)\)</span>：</p>
<p><span class="math display">\[\langle f_q(\mathbf{q}, m), f_k(\mathbf{k}, n) \rangle = g(\mathbf{q}, \mathbf{k}, m-n)\]</span></p>
<p>RoPE 发现：这个函数 <span class="math inline">\(f\)</span> 正是<strong>旋转函数</strong>。假设嵌入维度 <span class="math inline">\(d=2\)</span>，对位置 <span class="math inline">\(m\)</span> 上的向量 <span class="math inline">\(\mathbf{q}\)</span> 旋转 <span class="math inline">\(m\theta\)</span>，对位置 <span class="math inline">\(n\)</span> 上的 <span class="math inline">\(\mathbf{k}\)</span> 旋转 <span class="math inline">\(n\theta\)</span>：</p>
<p><span class="math display">\[f_q(\mathbf{q}, m) = R_{m\theta} \cdot \mathbf{q}, \quad f_k(\mathbf{k}, n) = R_{n\theta} \cdot \mathbf{k}\]</span></p>
<p>利用三角恒等式 <span class="math inline">\(\cos A \cos B + \sin A \sin B = \cos(A-B)\)</span> 和 <span class="math inline">\(\sin A \cos B - \cos A \sin B = \sin(A-B)\)</span>，可以证明：</p>
<p><span class="math display">\[\langle f_q(\mathbf{q}, m), f_k(\mathbf{k}, n) \rangle = \mathbf{q}^T \cdot R_{(m-n)\theta} \cdot \mathbf{k}\]</span></p>
<p>内积结果中的旋转矩阵仅依赖 <span class="math inline">\((m-n)\)</span>，<strong>绝对位置 <span class="math inline">\(m\)</span>、<span class="math inline">\(n\)</span> 消失了</strong>。这就是 RoPE 被称为”旋转位置编码”的原因——位置信息通过旋转注入，内积自动只保留相对位置。</p>
<p>为了将我们在二维空间中的结果推广到任意 <span class="math inline">\(\boldsymbol{x}_i \in \mathbb{R}^d\)</span>（其中 <span class="math inline">\(d\)</span> 为偶数），我们将 <span class="math inline">\(d\)</span> 维空间划分为 <span class="math inline">\(d/2\)</span> 个子空间，并利用内积的线性性质将它们组合起来，将 <span class="math inline">\(f_{\{q,k\}}\)</span> 转化为：</p>
<p><span class="math display">\[
f_{\{q,k\}}(\boldsymbol{x}_m, m) = \boldsymbol{R}^d_{\Theta,m} \boldsymbol{W}_{\{q,k\}} \boldsymbol{x}_m
\]</span></p>
<p>其中</p>
<p><span class="math display">\[
\boldsymbol{R}^d_{\Theta,m} =
\begin{pmatrix}
\cos m\theta_1 &amp; -\sin m\theta_1 &amp; 0 &amp; 0 &amp; \cdots &amp; 0 &amp; 0 \\
\sin m\theta_1 &amp; \cos m\theta_1 &amp; 0 &amp; 0 &amp; \cdots &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \cos m\theta_2 &amp; -\sin m\theta_2 &amp; \cdots &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; \sin m\theta_2 &amp; \cos m\theta_2 &amp; \cdots &amp; 0 &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots &amp; \vdots \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots &amp; \cos m\theta_{d/2} &amp; -\sin m\theta_{d/2} \\
0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots &amp; \sin m\theta_{d/2} &amp; \cos m\theta_{d/2}
\end{pmatrix}
\]</span></p>
<p>是旋转矩阵，其预定义参数为 <span class="math inline">\(\Theta = \{\theta_i = 10000^{-2(i-1)/d}, i \in [1, 2, ..., d/2]\}\)</span>。将我们的 RoPE 应用于自注意力机制，我们得到：</p>
<p><span class="math display">\[
\boldsymbol{q}_m^{\intercal} \boldsymbol{k}_n = (\boldsymbol{R}^d_{\Theta,m} \boldsymbol{W}_q \boldsymbol{x}_m)^{\intercal} (\boldsymbol{R}^d_{\Theta,n} \boldsymbol{W}_k \boldsymbol{x}_n) = \boldsymbol{x}^{\intercal} \boldsymbol{W}_q \boldsymbol{R}^d_{\Theta,n-m} \boldsymbol{W}_k \boldsymbol{x}_n
\]</span></p>
</section>
<section id="频率设计多频率覆盖不同距离" class="level4">
<h4 class="anchored" data-anchor-id="频率设计多频率覆盖不同距离">频率设计：多频率覆盖不同距离</h4>
<p>对于 <span class="math inline">\(d\)</span> 维向量，RoPE 将维度两两配对，共 <span class="math inline">\(d/2\)</span> 对。第 <span class="math inline">\(i\)</span> 对使用的旋转频率为：</p>
<p><span class="math display">\[\theta_i = 10000^{-2i/d}, \quad i = 0, 1, ..., d/2 - 1\]</span></p>
<p>这个频率设计的精妙之处：</p>
<ul>
<li><strong>低维度（<span class="math inline">\(i\)</span> 小）</strong>：<span class="math inline">\(\theta_i\)</span> 接近 1，频率高，旋转快 → 擅长捕捉<strong>短距离依赖</strong></li>
<li><strong>高维度（<span class="math inline">\(i\)</span> 大）</strong>：<span class="math inline">\(\theta_i\)</span> 接近 0，频率低，旋转慢 → 擅长捕捉<strong>长距离依赖</strong></li>
</ul>
<p>由此，RoPE 用一组从高到低的频率同时建模了不同的距离尺度。</p>
</section>
<section id="完整的逐对旋转形式" class="level4">
<h4 class="anchored" data-anchor-id="完整的逐对旋转形式">完整的逐对旋转形式</h4>
<p>对于位置 <span class="math inline">\(m\)</span> 上的向量 <span class="math inline">\(\mathbf{x} = [x_0, x_1, x_2, x_3, ..., x_{d-1}]\)</span>，RoPE 对每一对维度施加旋转：</p>
<p><span class="math display">\[\text{RoPE}(\mathbf{x}, m) = \begin{pmatrix}
x_0 \cos(m\theta_0) - x_1 \sin(m\theta_0) \\
x_1 \cos(m\theta_0) + x_0 \sin(m\theta_0) \\
x_2 \cos(m\theta_1) - x_3 \sin(m\theta_1) \\
x_3 \cos(m\theta_1) + x_2 \sin(m\theta_1) \\
\vdots
\end{pmatrix}\]</span></p>
<p>在 Self-Attention 中，RoPE 仅作用于 Q 和 K（V 不施加位置编码）：</p>
<p><span class="math display">\[\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{\text{RoPE}(Q, m) \cdot \text{RoPE}(K, n)^T}{\sqrt{d}}\right) V\]</span></p>
</section>
<section id="本项目的实现" class="level4">
<h4 class="anchored" data-anchor-id="本项目的实现">本项目的实现</h4>
<ul>
<li>频率计算：<span class="math inline">\(\text{freqs}_i = \theta^{-2i/d_k}\)</span>，其中 <span class="math inline">\(i = 0, 1, ..., d_k/2 - 1\)</span></li>
<li>预计算所有位置的正弦/余弦值并缓存（<code>cos_cache</code>、<code>sin_cache</code>）</li>
<li>前向传播时通过索引查找对应位置的正余弦值，使用高效的两两旋转公式：
<ul>
<li><span class="math inline">\(x'_{2i} = x_{2i} \cos(\text{pos}) - x_{2i+1} \sin(\text{pos})\)</span></li>
<li><span class="math inline">\(x'_{2i+1} = x_{2i} \sin(\text{pos}) + x_{2i+1} \cos(\text{pos})\)</span></li>
</ul></li>
</ul>
<p>RoPE 相比其他位置编码有五个显著优势：</p>
<ol type="1">
<li><strong>天然相对位置</strong>：内积仅依赖相对位置，适合语言建模</li>
<li><strong>良好的外推性</strong>：配合 NTK/YaRN 等方法可泛化到更长序列</li>
<li><strong>计算高效</strong>：无需额外的位置嵌入参数，仅做旋转操作</li>
<li><strong>无额外参数</strong>：基于固定的三角函数，不增加可学习参数</li>
<li><strong>KV Cache 友好</strong>：缓存的 K 值无需因位置变化而重新计算位置编码</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> RoPE(nn.Module):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, theta, d_k, max_seq_len, device<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        freqs <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (theta <span class="op">**</span> (torch.arange(<span class="dv">0</span>, d_k, <span class="dv">2</span>).<span class="bu">float</span>() <span class="op">/</span> d_k))   <span class="co"># [d_k//2]</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        positions <span class="op">=</span> torch.arange(max_seq_len)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        sinusoids <span class="op">=</span> torch.outer(positions, freqs)                         <span class="co"># [max_seq_len, d_k//2]</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.register_buffer(<span class="st">"cos_cache"</span>, sinusoids.cos(), persistent<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.register_buffer(<span class="st">"sin_cache"</span>, sinusoids.sin(), persistent<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x, token_positions):</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        cos <span class="op">=</span> <span class="va">self</span>.cos_cache[token_positions].to(x.dtype)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        sin <span class="op">=</span> <span class="va">self</span>.sin_cache[token_positions].to(x.dtype)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        x_even, x_odd <span class="op">=</span> x[..., <span class="dv">0</span>::<span class="dv">2</span>], x[..., <span class="dv">1</span>::<span class="dv">2</span>]</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        out_even <span class="op">=</span> x_even <span class="op">*</span> cos <span class="op">-</span> x_odd <span class="op">*</span> sin</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>        out_odd  <span class="op">=</span> x_even <span class="op">*</span> sin <span class="op">+</span> x_odd <span class="op">*</span> cos</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        out <span class="op">=</span> torch.stack([out_even, out_odd], dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> out.flatten(<span class="op">-</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="softmax" class="level3">
<h3 class="anchored" data-anchor-id="softmax">5.6 Softmax</h3>
<p><strong>文件：</strong> <a href="basics/model/softmax.py">basics/model/softmax.py</a></p>
<p>数值稳定的 Softmax 实现：</p>
<p><span class="math display">\[\text{softmax}(x_i) = \frac{\exp(x_i - x_{\max})}{\sum_j \exp(x_j - x_{\max})}\]</span></p>
<p>通过减去最大值防止指数运算溢出。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(x: torch.Tensor, dim: <span class="bu">int</span>) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    x_max <span class="op">=</span> x.<span class="bu">max</span>(dim<span class="op">=</span>dim, keepdim<span class="op">=</span><span class="va">True</span>)[<span class="dv">0</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    x_exp <span class="op">=</span> torch.exp(x <span class="op">-</span> x_max)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x_exp <span class="op">/</span> x_exp.<span class="bu">sum</span>(dim<span class="op">=</span>dim, keepdim<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="sec-multi-head-attention" class="level3">
<h3 class="anchored" data-anchor-id="sec-multi-head-attention">5.7 Multi-Head Attention</h3>
<p><strong>文件：</strong> <a href="basics/model/multi_head_attention.py">basics/model/multi_head_attention.py</a></p>
<p>完整的因果多头注意力实现：</p>
<ol type="1">
<li><strong>线性投影</strong>：Q、K、V 分别通过独立的 Linear 层投影（无偏置）</li>
<li><strong>维度变换</strong>：<code>[batch, seq, d_model]</code> → <code>[batch, n_heads, seq, head_dim]</code></li>
<li><strong>RoPE 编码</strong>：对 Q 和 K 应用旋转位置编码</li>
<li><strong>缩放点积注意力</strong>：<span class="math inline">\(\text{Attention}(Q, K, V) = \text{softmax}(\frac{QK^T}{\sqrt{d_k}} + \text{mask})V\)</span></li>
<li><strong>因果掩码</strong>：使用 <code>torch.tril</code> 创建下三角掩码，确保每个位置只能关注其之前的 token</li>
<li><strong>输出投影</strong>：拼接所有注意力头后通过 W_o 线性层</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> scaled_dot_product_attention(query, key, value, mask<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    d_k <span class="op">=</span> query.size(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> torch.matmul(query, key.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>)) <span class="op">/</span> (d_k <span class="op">**</span> <span class="fl">0.5</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> mask <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        scores <span class="op">=</span> scores.masked_fill(mask <span class="op">==</span> <span class="dv">0</span>, <span class="bu">float</span>(<span class="st">"-inf"</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    attn_weights <span class="op">=</span> softmax(scores, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.matmul(attn_weights, value)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MultiHeadAttention(nn.Module):</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d_model, n_heads, theta, max_seq_len, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.n_heads <span class="op">=</span> n_heads</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.head_dim <span class="op">=</span> d_model <span class="op">//</span> n_heads</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W_q <span class="op">=</span> Linear(d_model, d_model, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W_k <span class="op">=</span> Linear(d_model, d_model, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W_v <span class="op">=</span> Linear(d_model, d_model, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.W_o <span class="op">=</span> Linear(d_model, d_model, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.rope <span class="op">=</span> RoPE(theta, <span class="va">self</span>.head_dim, max_seq_len, device<span class="op">=</span>device)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> _create_causal_mask(<span class="va">self</span>, seq_len, device):</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>        mask <span class="op">=</span> torch.tril(torch.ones(seq_len, seq_len, device<span class="op">=</span>device)).<span class="bu">bool</span>()</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> mask.unsqueeze(<span class="dv">0</span>).unsqueeze(<span class="dv">0</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x, token_positions<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>        mask <span class="op">=</span> <span class="va">self</span>._create_causal_mask(x.size(<span class="dv">1</span>), x.device)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>        B, S, _ <span class="op">=</span> x.shape</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>        Q <span class="op">=</span> <span class="va">self</span>.W_q(x).view(B, S, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>        K <span class="op">=</span> <span class="va">self</span>.W_k(x).view(B, S, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>        V <span class="op">=</span> <span class="va">self</span>.W_v(x).view(B, S, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> token_positions <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>            Q <span class="op">=</span> <span class="va">self</span>.rope(Q, token_positions)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>            K <span class="op">=</span> <span class="va">self</span>.rope(K, token_positions)</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>        attn_out <span class="op">=</span> scaled_dot_product_attention(Q, K, V, mask<span class="op">=</span>mask)</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>        attn_out <span class="op">=</span> attn_out.transpose(<span class="dv">1</span>, <span class="dv">2</span>).contiguous().view(B, <span class="op">-</span><span class="dv">1</span>, <span class="va">self</span>.d_model)</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.W_o(attn_out)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="swiglu" class="level3">
<h3 class="anchored" data-anchor-id="swiglu">5.8 SwiGLU</h3>
<p>SwiGLU 的核心思想是用<strong>门控机制（Gating）</strong>替代传统 FFN 中单一的激活函数（如 ReLU、GeLU）。标准 FFN 对输入直接做线性变换后通过激活函数，而 SwiGLU 将输入分别送入两条路径：一条经过 SiLU 激活作为”门”（gate），另一条保持线性作为”值”（value），两者逐元素相乘后再投影回原始维度。这种门控设计让网络能够<strong>自适应地控制信息流动</strong>——门的值接近 0 时阻断信息，接近 1 时放行，接近负值时不仅阻断还能反转符号，从而赋予模型更灵活的表达能力。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/SwiGLU.png" class="img-fluid figure-img"></p>
<figcaption>FFN vs SwiGLU</figcaption>
</figure>
</div>
<p><strong>文件：</strong> <a href="basics/model/SwiGLU.py">basics/model/SwiGLU.py</a></p>
<p>基于 <a href="https://arxiv.org/abs/2002.05202">Shazeer (2020)</a> 的 SwiGLU 激活：</p>
<p><span class="math display">\[\text{SwiGLU}(x) = W_2(\text{SiLU}(W_1(x)) \odot W_3(x))\]</span></p>
<p>其中 <span class="math inline">\(\text{SiLU}(x) = x \cdot \sigma(x)\)</span>（<span class="math inline">\(\sigma\)</span> 为 sigmoid 函数）。</p>
<ul>
<li><span class="math inline">\(W_1\)</span>：<code>d_model → d_ff</code>（gate 投影）</li>
<li><span class="math inline">\(W_3\)</span>：<code>d_model → d_ff</code>（value 投影）</li>
<li><span class="math inline">\(W_2\)</span>：<code>d_ff → d_model</code>（输出投影）</li>
<li>所有投影均无偏置</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> SwiGLU(nn.Module):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d_model, d_ff, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.w1 <span class="op">=</span> Linear(d_model, d_ff, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.w2 <span class="op">=</span> Linear(d_ff, d_model, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.w3 <span class="op">=</span> Linear(d_model, d_ff, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> silu(<span class="va">self</span>, x):</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x <span class="op">*</span> torch.sigmoid(x)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.w2(<span class="va">self</span>.silu(<span class="va">self</span>.w1(x)) <span class="op">*</span> <span class="va">self</span>.w3(x))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="transformer-block" class="level3">
<h3 class="anchored" data-anchor-id="transformer-block">5.9 Transformer Block</h3>
<p><strong>文件：</strong> <a href="basics/model/transformer_block.py">basics/model/transformer_block.py</a></p>
<p>采用 Pre-Norm 残差结构：</p>
<pre><code>x → RMSNorm → Multi-Head Attention (+RoPE) → + x (残差)
  → RMSNorm → SwiGLU → + x1 (残差) → output</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/Transformer_Block_Diagram.png" class="img-fluid figure-img"></p>
<figcaption>Transformer Block Diagram</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> transformer_block(nn.Module):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d_model, n_heads, theta, max_seq_len, d_ff, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.RMSnorm_1 <span class="op">=</span> RMSnorm(d_model, eps<span class="op">=</span><span class="fl">1e-5</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.RMSnorm_2 <span class="op">=</span> RMSnorm(d_model, eps<span class="op">=</span><span class="fl">1e-5</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.multi_head_attention <span class="op">=</span> MultiHeadAttention(d_model, n_heads, theta, max_seq_len, device, dtype)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.swiglu <span class="op">=</span> SwiGLU(d_model, d_ff, device, dtype)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        token_positions <span class="op">=</span> torch.arange(x.shape[<span class="dv">1</span>], device<span class="op">=</span>x.device)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        x1 <span class="op">=</span> <span class="va">self</span>.RMSnorm_1(x)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        x1 <span class="op">=</span> <span class="va">self</span>.multi_head_attention(x1, token_positions)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>        x1 <span class="op">=</span> x1 <span class="op">+</span> x                                    <span class="co"># 残差连接</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        x2 <span class="op">=</span> <span class="va">self</span>.RMSnorm_2(x1)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        x2 <span class="op">=</span> <span class="va">self</span>.swiglu(x2)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>        out <span class="op">=</span> x2 <span class="op">+</span> x1                                   <span class="co"># 残差连接</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> out</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="transformermodule" class="level3">
<h3 class="anchored" data-anchor-id="transformermodule">5.10 TransformerModule</h3>
<p><strong>文件：</strong> <a href="basics/model/transformermodule.py">basics/model/transformermodule.py</a></p>
<p>完整的 Transformer 模型将上述组件组合为端到端的语言模型：</p>
<pre><code>Token IDs → Embedding → N × TransformerBlock → RMSNorm → Linear(LM Head) → Logits</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/LLAMA架构图.png" class="img-fluid figure-img"></p>
<figcaption>LLAMA架构图</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TransformerModule(nn.Module):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, d_model, n_heads, theta, max_seq_len, d_ff, n_layers, vocab_size, device<span class="op">=</span><span class="va">None</span>, dtype<span class="op">=</span>torch.bfloat16):</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.embedding_module <span class="op">=</span> EmbeddingModule(vocab_size, d_model, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.transformer_blocks <span class="op">=</span> nn.ModuleList([</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>            transformer_block(d_model, n_heads, theta, max_seq_len, d_ff, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_layers)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.final_norm <span class="op">=</span> RMSnorm(d_model, eps<span class="op">=</span><span class="fl">1e-5</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.linear_module <span class="op">=</span> Linear(d_model, vocab_size, bias<span class="op">=</span><span class="va">False</span>, device<span class="op">=</span>device, dtype<span class="op">=</span>dtype)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.embedding_module(x)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> block <span class="kw">in</span> <span class="va">self</span>.transformer_blocks:</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> block(x)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.final_norm(x)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> <span class="va">self</span>.linear_module(x)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="pre-training-strategy" class="level2">
<h2 class="anchored" data-anchor-id="pre-training-strategy">6 Pre-training Strategy</h2>
<section id="optimizer" class="level3">
<h3 class="anchored" data-anchor-id="optimizer">6.1 Optimizer</h3>
<p><strong>文件：</strong> <a href="basics/train/adamw.py">basics/train/adamw.py</a></p>
<p><strong>AdamW 实现</strong></p>
<p>Adam 优化器（Kingma &amp; Ba, 2015）将<strong>动量（Momentum）</strong>和 <strong>RMSProp</strong> 两种思想结合：通过一阶动量 <span class="math inline">\(m_t\)</span>（梯度的指数移动平均）提供惯性、通过二阶动量 <span class="math inline">\(v_t\)</span>（梯度平方的指数移动平均）为每个参数提供自适应的学习率缩放。这使得 Adam 在稀疏梯度和非平稳目标上表现优异。</p>
<p>然而，Adam 中存在一个被忽视的问题：<strong>L2 正则化与权重衰减在 Adam 中不等价</strong>。在 SGD 中，对 loss 加 <span class="math inline">\(\frac{\lambda}{2}\|\theta\|^2\)</span>（L2 正则化）等价于更新时令 <span class="math inline">\(\theta \leftarrow \theta - \alpha\lambda\theta\)</span>（权重衰减）。但 Adam 的自适应学习率 <span class="math inline">\(\frac{1}{\sqrt{\hat{v}_t} + \epsilon}\)</span> 会作用于合并了 L2 的梯度，导致权重衰减的实际强度被每个参数的梯度历史扭曲——梯度大的参数反而受到更弱的正则化。这导致 Adam 的泛化能力往往不如 SGD。</p>
<p><strong>AdamW（Loshchilov &amp; Hutter, 2019）的核心思想</strong>：将权重衰减从自适应梯度更新中<strong>解耦（decouple）</strong>出来。具体而言：梯度保持 <span class="math inline">\(g_t = \nabla L\)</span>（不含正则化项），Adam 更新完成后再<strong>独立执行</strong>权重衰减 <span class="math inline">\(\theta \leftarrow \theta - \alpha \lambda \theta\)</span>。权重衰减与学习率、梯度统计三者独立，互不干扰。</p>
<p>自定义 AdamW 优化器基于 <a href="https://arxiv.org/abs/1711.05101">Loshchilov &amp; Hutter (2019)</a>，将权重衰减从 Adam 的梯度更新中解耦：</p>
<p><strong>一阶/二阶动量更新：</strong></p>
<p><span class="math display">\[m_t = \beta_1 m_{t-1} + (1-\beta_1) g_t\]</span> <span class="math display">\[v_t = \beta_2 v_{t-1} + (1-\beta_2) g_t^2\]</span></p>
<p><strong>偏差修正：</strong></p>
<p><span class="math display">\[\hat{m}_t = \frac{m_t}{1 - \beta_1^t}, \quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}\]</span></p>
<p><strong>参数更新（Adam）：</strong></p>
<p><span class="math display">\[\theta_t = \theta_{t-1} - \alpha \cdot \frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}\]</span></p>
<p><strong>解耦权重衰减（独立执行）：</strong></p>
<p><span class="math display">\[\theta_t = \theta_t - \alpha \cdot \lambda \cdot \theta_{t-1}\]</span></p>
<p>其中 <span class="math inline">\(\lambda\)</span> 为 <code>weight_decay</code>，<span class="math inline">\(\alpha\)</span> 为学习率。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> AdamW(optim.Optimizer):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, params, lr<span class="op">=</span><span class="fl">1e-3</span>, betas<span class="op">=</span>(<span class="fl">0.9</span>, <span class="fl">0.999</span>), eps<span class="op">=</span><span class="fl">1e-8</span>, weight_decay<span class="op">=</span><span class="fl">1e-2</span>):</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        defaults <span class="op">=</span> <span class="bu">dict</span>(lr<span class="op">=</span>lr, betas<span class="op">=</span>betas, eps<span class="op">=</span>eps, weight_decay<span class="op">=</span>weight_decay)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>(params, defaults)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> step(<span class="va">self</span>):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> group <span class="kw">in</span> <span class="va">self</span>.param_groups:</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> p <span class="kw">in</span> group[<span class="st">'params'</span>]:</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> p.grad <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">continue</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                grad <span class="op">=</span> p.grad.data</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>                state <span class="op">=</span> <span class="va">self</span>.state[p]</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> <span class="bu">len</span>(state) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                    state[<span class="st">'step'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>                    state[<span class="st">'m'</span>] <span class="op">=</span> torch.zeros_like(p.data)   <span class="co"># 一阶动量</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>                    state[<span class="st">'v'</span>] <span class="op">=</span> torch.zeros_like(p.data)   <span class="co"># 二阶动量</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>                m, v <span class="op">=</span> state[<span class="st">'m'</span>], state[<span class="st">'v'</span>]</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>                beta1, beta2 <span class="op">=</span> group[<span class="st">'betas'</span>]</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>                state[<span class="st">'step'</span>] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Adam 更新（动量 + 偏差修正）</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>                m.mul_(beta1).add_(grad, alpha<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> beta1)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>                v.mul_(beta2).addcmul_(grad, grad, value<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> beta2)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>                bias_correction1 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> beta1 <span class="op">**</span> state[<span class="st">'step'</span>]</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>                bias_correction2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> beta2 <span class="op">**</span> state[<span class="st">'step'</span>]</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>                step_size <span class="op">=</span> group[<span class="st">'lr'</span>] <span class="op">/</span> bias_correction1</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>                denom <span class="op">=</span> (v <span class="op">/</span> bias_correction2).sqrt().add_(group[<span class="st">'eps'</span>])</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>                p.data.addcdiv_(m, denom, value<span class="op">=-</span>step_size)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>                <span class="co"># 解耦权重衰减</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>                p.data.add_(p.data, alpha<span class="op">=-</span>group[<span class="st">'weight_decay'</span>] <span class="op">*</span> group[<span class="st">'lr'</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="crossentropyloss" class="level3">
<h3 class="anchored" data-anchor-id="crossentropyloss">6.2 CrossEntropyLoss</h3>
<p><strong>文件：</strong> <a href="basics/train/cross_entropy.py">basics/train/cross_entropy.py</a></p>
<p>自定义实现的交叉熵损失，采用数值稳定的 log-softmax 计算：</p>
<p><span class="math display">\[\mathcal{L} = -\frac{1}{B \cdot S}\sum_{i=1}^{B\cdot S} \log P(y_i|x_i)\]</span></p>
<p>其中数值稳定的 log-softmax 计算为：</p>
<p><span class="math display">\[\log\text{softmax}(x_i) = (x_i - x_{\max}) - \log\left(\sum_j \exp(x_j - x_{\max})\right)\]</span></p>
<p><strong>输入输出格式：</strong> - 输入 <code>logits</code>：<code>[batch, seq, vocab_size]</code> - 目标 <code>targets</code>：<code>[batch, seq]</code>（真实 token ID） - 输出：标量损失值（所有 token 位置的平均值）</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CrossEntropyLoss:</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, <span class="bu">input</span>: torch.Tensor, target: torch.Tensor):</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>        <span class="co"># input: [batch, seq, vocab_size] -&gt; [batch*seq, vocab]</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>        <span class="co"># target: [batch, seq] -&gt; [batch*seq]</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>        batch, seq, vocab <span class="op">=</span> <span class="bu">input</span>.shape</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">input</span> <span class="op">=</span> <span class="bu">input</span>.view(batch <span class="op">*</span> seq, vocab)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>        target <span class="op">=</span> target.view(batch <span class="op">*</span> seq)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 数值稳定的 log_softmax</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        max_logits <span class="op">=</span> torch.<span class="bu">max</span>(<span class="bu">input</span>, dim<span class="op">=</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>).values</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        input_shifted <span class="op">=</span> <span class="bu">input</span> <span class="op">-</span> max_logits</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        log_sum_exp <span class="op">=</span> torch.log(torch.<span class="bu">sum</span>(torch.exp(input_shifted), dim<span class="op">=</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>        log_softmax_out <span class="op">=</span> input_shifted <span class="op">-</span> log_sum_exp</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>        log_p <span class="op">=</span> log_softmax_out[<span class="bu">range</span>(batch <span class="op">*</span> seq), target]</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> <span class="op">-</span>torch.<span class="bu">sum</span>(log_p) <span class="op">/</span> (batch <span class="op">*</span> seq)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> loss</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="dataloader" class="level3">
<h3 class="anchored" data-anchor-id="dataloader">6.3 DataLoader</h3>
<p><strong>文件：</strong> <a href="basics/train/dataloader.py">basics/train/dataloader.py</a></p>
<p>语言模型的训练采用<strong>下一 token 预测</strong>（next-token prediction）任务：</p>
<ul>
<li><strong>训练批次</strong>：随机采样 <span class="math inline">\(B\)</span> 个起始位置，取 <span class="math inline">\(x = \text{data}[i:i+L]\)</span>，<span class="math inline">\(y = \text{data}[i+1:i+L+1]\)</span>
<ul>
<li>其中 <span class="math inline">\(B\)</span> 为 <code>batch_size</code>，<span class="math inline">\(L\)</span> 为 <code>context_length</code></li>
</ul></li>
<li><strong>验证批次</strong>：按顺序遍历整个验证集，每次返回连续的 <span class="math inline">\(B \times L\)</span> 个 token</li>
</ul>
<p>这种设计使得模型在每个位置上都需要预测下一个 token，即语言模型的标准自监督训练方式。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> DataLoader:</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, dataset, batch_size, context_length, shuffle<span class="op">=</span><span class="va">True</span>, device<span class="op">=</span><span class="st">"cpu"</span>):</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.data <span class="op">=</span> dataset</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.batch_size <span class="op">=</span> batch_size</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.context_length <span class="op">=</span> context_length</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> get_train_batch_data(<span class="va">self</span>):</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        max_start <span class="op">=</span> <span class="va">self</span>.data_len <span class="op">-</span> <span class="va">self</span>.context_length</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>        idxs <span class="op">=</span> np.random.randint(<span class="dv">0</span>, max_start, size<span class="op">=</span>(<span class="va">self</span>.batch_size,))</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> np.stack([<span class="va">self</span>.data[i : i <span class="op">+</span> <span class="va">self</span>.context_length] <span class="cf">for</span> i <span class="kw">in</span> idxs])</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> np.stack([<span class="va">self</span>.data[i<span class="op">+</span><span class="dv">1</span> : i <span class="op">+</span> <span class="va">self</span>.context_length <span class="op">+</span> <span class="dv">1</span>] <span class="cf">for</span> i <span class="kw">in</span> idxs])</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.tensor(x), torch.tensor(y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="lr_cosine_shedule" class="level3">
<h3 class="anchored" data-anchor-id="lr_cosine_shedule">6.4 lr_cosine_shedule</h3>
<p><strong>文件：</strong> <a href="basics/train/lr_cosine_shedule.py">basics/train/lr_cosine_shedule.py</a></p>
<p>采用<strong>线性预热 + 余弦退火</strong>策略：</p>
<p><span class="math display">\[\text{lr}(t) = \begin{cases}
\eta_{\max} \cdot \frac{t}{t_{\text{warmup}}} &amp; t &lt; t_{\text{warmup}} \\[6pt]
\eta_{\min} + \frac{1}{2}(\eta_{\max} - \eta_{\min}) \left(1 + \cos\left(\pi \cdot \frac{t - t_{\text{warmup}}}{t_{\text{cycle}} - t_{\text{warmup}}}\right)\right) &amp; t_{\text{warmup}} \leq t \leq t_{\text{cycle}} \\[6pt]
\eta_{\min} &amp; t &gt; t_{\text{cycle}}
\end{cases}\]</span></p>
<p>其中 <span class="math inline">\(\eta_{\max} = 4\times10^{-4}\)</span>，<span class="math inline">\(\eta_{\min} = 4\times10^{-5}\)</span>，<span class="math inline">\(t_{\text{warmup}} = 500\)</span>。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CosineSchedule:</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, max_learning_rate, min_learning_rate, warmup_iters, cosine_cycle_iters):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.max_learning_rate <span class="op">=</span> max_learning_rate</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.min_learning_rate <span class="op">=</span> min_learning_rate</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.warmup_iters <span class="op">=</span> warmup_iters</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.cosine_cycle_iters <span class="op">=</span> cosine_cycle_iters</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__call__</span>(<span class="va">self</span>, it):</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> it <span class="op">&lt;</span> <span class="va">self</span>.warmup_iters:</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">self</span>.max_learning_rate <span class="op">*</span> it <span class="op">/</span> <span class="va">self</span>.warmup_iters</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> it <span class="op">&gt;</span> <span class="va">self</span>.cosine_cycle_iters:</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">self</span>.min_learning_rate</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>            progress <span class="op">=</span> (it <span class="op">-</span> <span class="va">self</span>.warmup_iters) <span class="op">/</span> (<span class="va">self</span>.cosine_cycle_iters <span class="op">-</span> <span class="va">self</span>.warmup_iters)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">self</span>.min_learning_rate <span class="op">+</span> (<span class="dv">1</span> <span class="op">+</span> math.cos(math.pi <span class="op">*</span> progress)) <span class="op">*</span> <span class="op">\</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                   (<span class="va">self</span>.max_learning_rate <span class="op">-</span> <span class="va">self</span>.min_learning_rate) <span class="op">/</span> <span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="gradient_clip" class="level3">
<h3 class="anchored" data-anchor-id="gradient_clip">6.5 gradient_clip</h3>
<p><strong>文件：</strong> <a href="basics/train/gradient_clip.py">basics/train/gradient_clip.py</a></p>
<p>全局 L2 范数梯度裁剪，防止梯度爆炸：</p>
<p><span class="math display">\[g_{\text{clipped}} = \begin{cases}
g \cdot \frac{v}{\|g\|_2 + \epsilon} &amp; \text{if } \|g\|_2 &gt; v \\
g &amp; \text{otherwise}
\end{cases}\]</span></p>
<p>其中 <span class="math inline">\(v = 1.0\)</span> 为裁剪阈值，<span class="math inline">\(g\)</span> 为所有参数梯度的拼接。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> GradientClip:</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, parameters, max_l2_norm, epsilon<span class="op">=</span><span class="fl">1e-6</span>):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.parameters <span class="op">=</span> parameters</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.max_l2_norm <span class="op">=</span> max_l2_norm</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.epsilon <span class="op">=</span> epsilon</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__call__</span>(<span class="va">self</span>):</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>        grads <span class="op">=</span> [p.grad <span class="cf">for</span> p <span class="kw">in</span> <span class="va">self</span>.parameters <span class="cf">if</span> p.grad <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>]</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>        all_grads <span class="op">=</span> torch.cat([grad.flatten() <span class="cf">for</span> grad <span class="kw">in</span> grads])</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>        grad_l2 <span class="op">=</span> torch.norm(all_grads, <span class="dv">2</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> grad_l2 <span class="op">&gt;</span> <span class="va">self</span>.max_l2_norm:</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            clip_coeff <span class="op">=</span> <span class="va">self</span>.max_l2_norm <span class="op">/</span> (grad_l2 <span class="op">+</span> <span class="va">self</span>.epsilon)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> grad <span class="kw">in</span> grads:</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>                grad.mul_(clip_coeff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="pre-training" class="level2">
<h2 class="anchored" data-anchor-id="pre-training">7 Pre-Training</h2>
<section id="训练脚本" class="level3">
<h3 class="anchored" data-anchor-id="训练脚本">7.1 训练脚本</h3>
<p><strong>文件：</strong> <a href="basics/final_train.py">basics/final_train.py</a></p>
<p>每步训练执行以下操作：</p>
<ol type="1">
<li><strong>梯度累积</strong>：循环 <code>accumulation_steps</code> 次：
<ul>
<li>从 DataLoader 获取一个微批次</li>
<li>前向传播计算 logits</li>
<li>计算交叉熵损失并除以累积步数</li>
<li>反向传播累积梯度</li>
</ul></li>
<li><strong>学习率调度</strong>：根据余弦调度器更新当前步的学习率</li>
<li><strong>梯度裁剪</strong>：对所有参数梯度进行全局 L2 范数裁剪</li>
<li><strong>优化器更新</strong>：<code>optimizer.step()</code> + <code>optimizer.zero_grad()</code></li>
</ol>
<p>核心训练循环代码：</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(start_epoch, config[<span class="st">"epochs"</span>]):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    total_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(global_step <span class="op">+</span> <span class="dv">1</span>, config[<span class="st">"train_steps"</span>]):</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 梯度累积</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>        accumulated_loss <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> micro_step <span class="kw">in</span> <span class="bu">range</span>(config[<span class="st">"accumulation_steps"</span>]):</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>            x, y <span class="op">=</span> train_data_loader.get_train_batch_data()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>            x, y <span class="op">=</span> x.to(device), y.to(device)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>            logits <span class="op">=</span> model(x)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> loss_fn.forward(logits, y) <span class="op">/</span> config[<span class="st">"accumulation_steps"</span>]</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>            accumulated_loss <span class="op">+=</span> loss.item()</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 学习率调度</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>        new_lr <span class="op">=</span> lr_scheduler(global_step)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> param_group <span class="kw">in</span> optimizer.param_groups:</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>            param_group[<span class="st">'lr'</span>] <span class="op">=</span> new_lr</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 梯度裁剪</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>        GradientClip(model.parameters(), config[<span class="st">"grad_clip"</span>])()</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>        optimizer.step()</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>        total_loss <span class="op">+=</span> accumulated_loss</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>        global_step <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 每 10 步记录 W&amp;B</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> global_step <span class="op">%</span> <span class="dv">10</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>            wandb.log({<span class="st">"epoch"</span>: epoch, <span class="st">"step"</span>: global_step, <span class="st">"loss"</span>: accumulated_loss, <span class="st">"lr"</span>: new_lr})</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 每 1000 步验证 + 保存检查点</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> global_step <span class="op">%</span> <span class="dv">1000</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>            avg_val_loss <span class="op">=</span> evaluate_validation_loss(model, valid_data_loader, loss_fn, device, val_steps<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>            wandb.log({<span class="st">"epoch"</span>: epoch, <span class="st">"step"</span>: global_step, <span class="st">"val_loss"</span>: avg_val_loss})</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>            torch.save({</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>                <span class="st">'epoch'</span>: epoch, <span class="st">'step'</span>: global_step,</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>                <span class="st">'model_state_dict'</span>: model.state_dict(),</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>                <span class="st">'optimizer_state_dict'</span>: optimizer.state_dict(),</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>            }, <span class="ss">f"checkpoints/</span><span class="sc">{</span>timestamp<span class="sc">}</span><span class="ss">/model_step_</span><span class="sc">{</span>global_step<span class="sc">}</span><span class="ss">.pth"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="检查点与恢复" class="level3">
<h3 class="anchored" data-anchor-id="检查点与恢复">7.2 检查点与恢复</h3>
<p><strong>文件：</strong> <a href="basics/checkpoint.py">basics/checkpoint.py</a></p>
<ul>
<li>每 1000 步保存一次检查点</li>
<li>每个 epoch 结束额外保存一次检查点</li>
<li>检查点包含模型权重、优化器状态、当前 epoch / step 和 W&amp;B run id</li>
<li>支持从指定检查点恢复训练 (<a href="basics/final_train.py#L35-L45">final_train.py:35-45</a>)</li>
<li>检查点命名格式：<code>model_step_{step}.pth</code> / <code>model_epoch_{epoch}.pth</code></li>
</ul>
</section>
<section id="验证评估" class="level3">
<h3 class="anchored" data-anchor-id="验证评估">7.3 验证评估</h3>
<p>训练过程中每 1000 步进行一次验证评估（<a href="basics/final_train.py#L204">final_train.py:204</a>）：</p>
<ol type="1">
<li>将模型设为 <code>eval()</code> 模式</li>
<li>不计算梯度 (<code>torch.no_grad()</code>)</li>
<li>从验证集<strong>随机采样 1000 个批次</strong>（每批次按训练方式随机取偏移量）计算平均验证损失</li>
<li>将验证损失记录到 W&amp;B</li>
</ol>
<p>此外，每个 epoch 结束时会自动保存一次检查点。</p>
</section>
<section id="实验追踪" class="level3">
<h3 class="anchored" data-anchor-id="实验追踪">7.4 实验追踪</h3>
<p>使用 <strong>Weights &amp; Biases (W&amp;B)</strong> 进行实验追踪，记录以下指标：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指标</th>
<th>记录频率</th>
<th>含义</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>loss</code></td>
<td>每 10 步</td>
<td>训练损失（梯度累积后）</td>
</tr>
<tr class="even">
<td><code>lr</code></td>
<td>每 10 步</td>
<td>当前学习率</td>
</tr>
<tr class="odd">
<td><code>val_loss</code></td>
<td>每 1000 步</td>
<td>验证集交叉熵损失</td>
</tr>
</tbody>
</table>
</section>
<section id="推理" class="level3">
<h3 class="anchored" data-anchor-id="推理">7.5 推理</h3>
<p><strong>文件：</strong> <a href="basics/inference/inference.py">basics/inference/inference.py</a></p>
<p>推理采用自回归解码：</p>
<ol type="1">
<li><strong>温度缩放</strong>：将 logits 除以温度参数 <span class="math inline">\(T\)</span> 后使用 softmax 转换为概率分布</li>
<li><strong>Top-p 采样（核采样）</strong>：从累积概率超过阈值 <span class="math inline">\(p\)</span> 的最小 token 集合中随机采样</li>
<li><strong>自回归生成</strong>：将采样的 token 拼接回输入序列，重复生成直到达到最大长度</li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> temperature_scaling(logits, temperature<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    probabilities <span class="op">=</span> torch.softmax(logits[:, <span class="op">-</span><span class="dv">1</span>, :] <span class="op">/</span> temperature, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> probabilities</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> top_p_sampling(probabilities, top_p<span class="op">=</span><span class="fl">0.9</span>):</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    sort_probs, idx <span class="op">=</span> torch.sort(probabilities, dim<span class="op">=-</span><span class="dv">1</span>, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    cumulative <span class="op">=</span> torch.cumsum(sort_probs, dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> cumulative <span class="op">&gt;</span> top_p</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    mask[..., <span class="dv">1</span>:] <span class="op">=</span> mask[..., :<span class="op">-</span><span class="dv">1</span>].clone()     <span class="co"># 确保至少保留一个 token</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    mask[..., <span class="dv">0</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    sort_probs[mask] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    sort_probs.div_(sort_probs.<span class="bu">sum</span>(dim<span class="op">=-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    next_token_idx <span class="op">=</span> torch.multinomial(sort_probs, <span class="dv">1</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.gather(idx, dim<span class="op">=-</span><span class="dv">1</span>, index<span class="op">=</span>next_token_idx)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> decode_token(input_tokens, model, max_tokens_to_generate, top_p<span class="op">=</span><span class="fl">0.9</span>, temperature<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    input_tokens <span class="op">=</span> torch.tensor(input_tokens).unsqueeze(<span class="dv">0</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(max_tokens_to_generate):</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>            logits <span class="op">=</span> model(input_tokens)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>            probs <span class="op">=</span> temperature_scaling(logits, temperature)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>            next_token <span class="op">=</span> top_p_sampling(probs, top_p)</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>            input_tokens <span class="op">=</span> torch.cat([input_tokens, next_token], dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> input_tokens</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="pre-training-details" class="level2">
<h2 class="anchored" data-anchor-id="pre-training-details">8 Pre-Training details</h2>
<section id="训练配置" class="level3">
<h3 class="anchored" data-anchor-id="训练配置">8.1 训练配置</h3>
<ul>
<li>训练设备：CUDA GPU 4090</li>
<li>数据类型：bfloat16（混合精度），float32 用于需要高精度的操作（如 RMSNorm）</li>
<li>总训练 token 数：1,458,472,895（约 14.58 亿）</li>
</ul>
<section id="训练配置-1" class="level4">
<h4 class="anchored" data-anchor-id="训练配置-1">训练配置</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>超参数</th>
<th>值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>micro_batch_size</code></td>
<td>32</td>
<td>单步批次大小（受显存限制）</td>
</tr>
<tr class="even">
<td><code>effective_batch_size</code></td>
<td>256</td>
<td>等效批次大小</td>
</tr>
<tr class="odd">
<td><code>accumulation_steps</code></td>
<td>8</td>
<td>梯度累积步数</td>
</tr>
<tr class="even">
<td><code>max_learning_rate</code></td>
<td>4e-4</td>
<td>峰值学习率</td>
</tr>
<tr class="odd">
<td><code>min_learning_rate</code></td>
<td>4e-5</td>
<td>最小学习率</td>
</tr>
<tr class="even">
<td><code>lr_warmup_steps</code></td>
<td>500</td>
<td>学习率预热步数</td>
</tr>
<tr class="odd">
<td><code>weight_decay</code></td>
<td>0.1</td>
<td>权重衰减系数</td>
</tr>
<tr class="even">
<td><code>grad_clip</code></td>
<td>1.0</td>
<td>梯度裁剪的 L2 范数阈值</td>
</tr>
<tr class="odd">
<td><code>epochs</code></td>
<td>1</td>
<td>训练轮数（全量数据）</td>
</tr>
<tr class="even">
<td><code>context_length</code></td>
<td>768</td>
<td>上下文窗口</td>
</tr>
</tbody>
</table>
</section>
<section id="初始化参数" class="level4">
<h4 class="anchored" data-anchor-id="初始化参数">初始化参数：</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>参数</th>
<th>含义</th>
<th>值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>d_model</code></td>
<td>隐藏层维度</td>
<td>768</td>
</tr>
<tr class="even">
<td><code>n_heads</code></td>
<td>注意力头数</td>
<td>8</td>
</tr>
<tr class="odd">
<td><code>n_layers</code></td>
<td>Transformer 块数</td>
<td>8</td>
</tr>
<tr class="even">
<td><code>d_ff</code></td>
<td>FFN 中间层维度</td>
<td>2048</td>
</tr>
<tr class="odd">
<td><code>vocab_size</code></td>
<td>词汇表大小</td>
<td>32768</td>
</tr>
<tr class="even">
<td><code>max_seq_len</code></td>
<td>最大序列长度</td>
<td>768</td>
</tr>
<tr class="odd">
<td><code>rope_theta</code></td>
<td>RoPE 频率底数</td>
<td>10000.0</td>
</tr>
</tbody>
</table>
</section>
<section id="参数量" class="level4">
<h4 class="anchored" data-anchor-id="参数量">参数量：</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 39%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>组件</th>
<th>计算公式</th>
<th>参数量</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Embedding</td>
<td><code>vocab_size × d_model</code> = 32768 × 768</td>
<td>25,165,824</td>
</tr>
<tr class="even">
<td>Attention</td>
<td>4 × <code>d_model²</code> = 4 × 768²</td>
<td>2,359,296 × 8 = 18,874,368</td>
</tr>
<tr class="odd">
<td>SwiGLU</td>
<td>3 × <code>d_model × d_ff</code> = 3 × 768 × 2048</td>
<td>4,718,592 × 8 = 37,748,736</td>
</tr>
<tr class="even">
<td>RMSNorm</td>
<td><code>d_model</code> = 768</td>
<td>768 × 17 = 13,056</td>
</tr>
<tr class="odd">
<td>LM Head</td>
<td>与 Embedding 权重共享（tied）</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>合计</strong></td>
<td></td>
<td><strong>≈ 81.80M（约 80M）</strong></td>
</tr>
</tbody>
</table>
<p>其中 8 个 Transformer Block 共约 56.64M 参数，占总参数量的 69%；Embedding 层约 25.17M，占 31%。</p>
</section>
</section>
<section id="bpe" class="level3">
<h3 class="anchored" data-anchor-id="bpe">8.2 BPE</h3>
<p>BPE（Byte-Pair Encoding）分词器的训练与数据编码是预训练的前置步骤。本项目在 OpenWebText 数据集上的实际运行耗时：</p>
<ul>
<li><strong>BPE 训练</strong>：从原始文本语料中学习词汇表（词表大小 32768），约耗时 <strong>2 小时</strong>，占内存约 <strong>64 GB</strong></li>
<li><strong>数据编码</strong>：将训练好的 BPE 模型应用于全部语料（约 14.58 亿 token），将原始文本转换为 token ID 序列，约耗时 <strong>20 分钟</strong></li>
</ul>
</section>
<section id="pre-training-1" class="level3">
<h3 class="anchored" data-anchor-id="pre-training-1">8.3 pre-training</h3>
<p>模型（80M 参数）在单张 NVIDIA RTX 4090（24 GB 显存）上完成 1 个 epoch 的完整预训练，共处理约 14.58 亿 token，训练耗时约 <strong>6 小时</strong>。以下为训练过程中的关键曲线：</p>
<ul>
<li><strong>训练损失曲线</strong>：损失从约 10.4（接近 <span class="math inline">\(\ln(32768)\)</span>，即初始均匀分布对应的交叉熵）逐步下降，训练初期下降最快，随后进入平稳下降阶段，最终在3.45附近，未观察到明显的过拟合或发散迹象。</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/loss.png" class="img-fluid figure-img"></p>
<figcaption>损失曲线</figcaption>
</figure>
</div>
<ul>
<li><strong>验证损失曲线</strong>：每 1000 步评估一次验证损失，整体趋势与训练损失一致且始终略高于训练损失，二者之间未见明显 gap，说明模型泛化良好。</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/val_loss.png" class="img-fluid figure-img"></p>
<figcaption>验证损失曲线</figcaption>
</figure>
</div>
<ul>
<li><strong>学习率曲线</strong>：采用线性预热（前 500 步）+ 余弦退火策略，学习率从 0 线性增至峰值 4e-4 后沿余弦曲线衰减至最小值 4e-5。</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/lr.png" class="img-fluid figure-img"></p>
<figcaption>学习率曲线</figcaption>
</figure>
</div>
</section>
<section id="结果" class="level3">
<h3 class="anchored" data-anchor-id="结果">8.4 结果</h3>
<p>预训练完成后，我们从验证集中挑选了 4 个不同领域的文本片段（新闻时事、技术科学、文学叙事、百科知识），分别截取其中一部分作为 Prompt 输入模型进行续写，观察模型的生成能力和局限性。</p>
<p><strong>生成样例</strong>（模型输出续写部分）：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>领域</th>
<th>Prompt（截取）</th>
<th>模型续写（截取）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>新闻时事</td>
<td><em>(CNN) – A gunman critically injured a doctor at Johns Hopkins Hospital in Baltimore, Maryland, and later killed himself and his mother, police say.</em></td>
<td>A spokesman for the Ronald Johns Hopkins Medical Center told the Washington Post at the time, “We have thoughts on our deceased patient.” The director of the facility, Peter Davie, said at a hearing… President Trump said last week that he was aware of the safety concerns with a female spokesperson…</td>
</tr>
<tr class="even">
<td>技术科学</td>
<td><em>In recent years, research on quantum information has achieved a series of remarkable results.</em></td>
<td>Quantum energy in quantum systems is known as “a quantum particle of quantum quantity” and by talking about atomic combinations in the language. In the discovery of this paper we show how the electric field and the quantum combination can respond to quantum activities…</td>
</tr>
<tr class="odd">
<td>文学叙事</td>
<td><em>“Back, are you?” said Aberforth. “What happened here?” Albus replied, though he could already guess.</em></td>
<td>“I’m keeping you all out here.” Her voice turned to roar, but she turned and the shadows settled to shadows. Albus could feel it, but it was too many things. “Are you still in prison?” his voice caught up with his face, but his eyes still looked just the same as his father’s…</td>
</tr>
<tr class="even">
<td>百科知识</td>
<td><em>Traces of ancient civilization to be searched in Adıyaman. Following the expropriation works, excavation activities will be carried out in the ancient city of Perre, one of the five big cities of the Commagene civilization.</em></td>
<td>With its cultivation the most clearly defined areas were Kazakhstan (organic and ancient) and southeast Syria (recognised by Istanbul). In recent years, this number has gone from 10,000 to 60,000, especially the Brahmin cities (Paramural, Stadebel, Pina Galathi, Samajtar…)</td>
</tr>
</tbody>
</table>
<p>模型能够生成语法通顺、结构合理的英文文本，续写内容在句法和局部语义上基本连贯。但受限于 80M 参数量级和仅 1 个 epoch 的训练，输出存在以下局限：</p>
<ul>
<li><ol type="1">
<li>事实性错误较多，如编造人名、地名、事件；</li>
</ol></li>
<li><ol start="2" type="1">
<li>长距离逻辑一致性较弱，主题漂移明显；</li>
</ol></li>
<li><ol start="3" type="1">
<li>偶有重复生成或提前输出 <code>&lt;|endoftext|&gt;</code> 终止符。</li>
</ol></li>
</ul>
</section>
</section>
<section id="实验" class="level2">
<h2 class="anchored" data-anchor-id="实验">9 实验</h2>
<section id="chinchilla-缩放定律" class="level3">
<h3 class="anchored" data-anchor-id="chinchilla-缩放定律">9.1 Chinchilla 缩放定律</h3>
<p>在大语言模型预训练中，一个核心问题是如何在<strong>给定的计算预算（FLOPs）</strong>下，最优地分配<strong>模型参数量 <span class="math inline">\(N\)</span></strong> 和<strong>训练数据量 <span class="math inline">\(D\)</span></strong>（token 数）。DeepMind 的 Chinchilla 论文（Hoffmann et al., 2022）通过大规模实验系统性地回答了这个问题。</p>
<p><strong>背景：Kaplan et al.&nbsp;(2020) 的结论</strong></p>
<p>OpenAI 的 Kaplan et al.&nbsp;(2020) 最早研究了缩放定律，其主要结论为：给定计算预算 <span class="math inline">\(C\)</span>，模型大小的最优缩放指数为 <span class="math inline">\(N_{\text{opt}} \propto C^{0.73}\)</span>，而数据量的最优缩放指数为 <span class="math inline">\(D_{\text{opt}} \propto C^{0.27}\)</span>。这意味着计算预算增加时，模型大小应比数据量增长得更快。这一结论深刻影响了 GPT-3 等大模型的训练策略——当时的普遍做法是训练越来越大的模型，但在相对较少的数据上训练不足（undertraining）。</p>
<p><strong>Chinchilla 的三条实验路线</strong></p>
<p>Chinchilla 论文通过三条独立路线得出了不同于 Kaplan et al.&nbsp;的结论：</p>
<ol type="1">
<li><strong>方法一：固定模型大小，变化数据量</strong>。对 9 种不同大小的模型（70M 至 16B），分别在 4 种不同数据量上训练，观察损失随 <span class="math inline">\(N\)</span> 和 <span class="math inline">\(D\)</span> 的变化。</li>
<li><strong>方法二：IsoFLOP 剖面</strong>。固定 9 种不同的计算预算（<span class="math inline">\(6 \times 10^{17}\)</span> 至 <span class="math inline">\(3 \times 10^{21}\)</span> FLOPs），对每种预算变化模型大小，寻找使损失最小的最优 <span class="math inline">\(N\)</span> 和 <span class="math inline">\(D\)</span> 组合。</li>
<li><strong>方法三：参数化损失函数拟合</strong>。将损失建模为 <span class="math inline">\(L(N, D) = E + \frac{A}{N^\alpha} + \frac{B}{D^\beta}\)</span>，通过拟合所有实验数据点确定参数 <span class="math inline">\(E\)</span>、<span class="math inline">\(A\)</span>、<span class="math inline">\(B\)</span>、<span class="math inline">\(\alpha\)</span>、<span class="math inline">\(\beta\)</span>，进而推导出任意计算预算下的最优配置。</li>
</ol>
<p>三种方法得出了高度一致的结论。</p>
<p><strong>核心结论</strong></p>
<p>Chinchilla 的最终参数拟合结果为：</p>
<p><span class="math display">\[L(N, D) = 1.69 + \frac{406.4}{N^{0.34}} + \frac{410.7}{D^{0.28}}\]</span></p>
<p>其中 <span class="math inline">\(E = 1.69\)</span> 为不可约损失（数据的熵），<span class="math inline">\(\alpha = 0.34\)</span> 和 <span class="math inline">\(\beta = 0.28\)</span> 分别控制模型容量和数据量对损失下降的贡献速率。由此推导出计算最优配置：</p>
<p><span class="math display">\[N_{\text{opt}} \propto C^{0.50}, \quad D_{\text{opt}} \propto C^{0.50}\]</span></p>
<p>即<strong>模型大小和训练数据量应当等比例缩放</strong>——计算预算翻倍时，模型参数量和训练 token 数应同时翻倍。这一结论与 Kaplan et al.&nbsp;的 <span class="math inline">\(N_{\text{opt}} \propto C^{0.73}\)</span> 有本质区别。</p>
<p><strong>Chinchilla 缩放定律验证</strong></p>
<p>本项目训练了 80M 参数的模型，计算量 6h 4090，处理了约 14.58 亿 token（1 个 epoch），loss = 3.45 。 <span class="math inline">\(D/N \approx 19\)</span>：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 39%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>组件</th>
<th>计算公式</th>
<th>参数量</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Embedding</td>
<td><code>vocab_size × d_model</code> = 32768 × 768</td>
<td>25,165,824</td>
</tr>
<tr class="even">
<td>Attention</td>
<td>4 × <code>d_model²</code> = 4 × 768²</td>
<td>2,359,296 × 8 = 18,874,368</td>
</tr>
<tr class="odd">
<td>SwiGLU</td>
<td>3 × <code>d_model × d_ff</code> = 3 × 768 × 2048</td>
<td>4,718,592 × 8 = 37,748,736</td>
</tr>
<tr class="even">
<td>RMSNorm</td>
<td><code>d_model</code> = 768</td>
<td>768 × 17 = 13,056</td>
</tr>
<tr class="odd">
<td>LM Head</td>
<td>与 Embedding 权重共享（tied）</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>合计</strong></td>
<td></td>
<td><strong>≈ 81.80M（约 80M）</strong></td>
</tr>
</tbody>
</table>
<p>此外，本项目还训练了一个更大的 185M 参数模型作为对比，计算量 6h 4090，处理了约 6.3 亿 token，loss = 3.35 ， <span class="math inline">\(D/N \approx 3.4\)</span>，</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 39%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>组件</th>
<th>计算公式</th>
<th>参数量</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Embedding</td>
<td><code>vocab_size × d_model</code> = 32768 × 1024</td>
<td>33,554,432</td>
</tr>
<tr class="even">
<td>Attention</td>
<td>4 × <code>d_model²</code> = 4 × 1024²</td>
<td>4,194,304 × 12 = 50,331,648</td>
</tr>
<tr class="odd">
<td>SwiGLU</td>
<td>3 × <code>d_model × d_ff</code> = 3 × 1024 × 3072</td>
<td>9437184 × 12 = 113246208</td>
</tr>
<tr class="even">
<td>RMSNorm</td>
<td><code>d_model</code> = 1024</td>
<td>1024 × 25 = 25,600</td>
</tr>
<tr class="odd">
<td>LM Head</td>
<td>与 Embedding 权重共享（tied）</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>合计</strong></td>
<td></td>
<td><strong>≈ 197.13M（约 197M）</strong></td>
</tr>
</tbody>
</table>
<p>从主观上来看，80M 参数模型的 <span class="math inline">\(D/N\)</span> 比较接近最优值（约 20），而 197M 参数模型的 <span class="math inline">\(D/N\)</span> 明显偏低（约 3），因此 80M 模型的训练效率更高，损失更低。</p>
<p>为了证明这一点，我从验证集中抽出八个类别1000条数据的子集，分别用两个模型进行推理，并用deepseekv4模型对结果进行打分来评判模型的生成质量，结果如下：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>轮数</th>
<th>80M（win）</th>
<th>197M（win）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>483</td>
<td>517</td>
</tr>
<tr class="even">
<td>2</td>
<td>471</td>
<td>529</td>
</tr>
<tr class="odd">
<td>3</td>
<td>490</td>
<td>510</td>
</tr>
</tbody>
</table>
<p><strong>实验结果分析与讨论</strong></p>
<p>实验结果显示 80M 与 197M 模型在生成质量上整体接近，197M 模型甚至略占优势（三轮 pairwise 评测平均胜率约 51.9% vs 48.1%）。这与最初的直觉预期——80M 模型的 <span class="math inline">\(D/N \approx 18.3\)</span> 更接近 Chinchilla 最优比例 20，应当明显优于 <span class="math inline">\(D/N \approx 3.4\)</span> 的 197M 模型——并不一致。</p>
<p>然而，重新审视 Chinchilla 论文的 IsoFLOP 曲线后可以发现，这一结果实际上与 Chinchilla 的结论完全吻合。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/Chinchilla.png" class="img-fluid figure-img"></p>
<figcaption>Chinchilla IsoFLOP 曲线</figcaption>
</figure>
</div>
<p>本实验的计算条件为单张 RTX 4090 训练约 6 小时，有效算力预估在 <span class="math inline">\({\sim}1\times10^{18}\)</span> FLOPs 量级。对应 Chinchilla IsoFLOP 曲线，该算力水平下的最优模型规模恰好在 100M 参数量级附近，且曲线在 100M 右侧已趋于平缓——这意味着在 80M 到 197M 区间内，模型损失对参数量的变化并不敏感。因此，197M 模型与 80M 模型表现相近甚至略优，是 IsoFLOP 曲线平坦区域的必然结果，而非对 Chinchilla 定律的反驳。本实验从侧面验证了 Chinchilla 的结论，同时也揭示了一个重要的实践启示：<strong>在低算力预算（如 <span class="math inline">\({\sim}10^{18}\)</span> FLOPs）下，最优 <span class="math inline">\(D/N\)</span> 比例远小于经典建议的 20，应当优先保证模型参数量，而非追求数据量的匹配。</strong></p>
</section>
<section id="kv_cache" class="level3">
<h3 class="anchored" data-anchor-id="kv_cache">9.2 kv_cache</h3>
<section id="kv-cache-的核心思想" class="level4">
<h4 class="anchored" data-anchor-id="kv-cache-的核心思想">KV Cache 的核心思想</h4>
<p>KV Cache 是 Transformer 解码器在自回归推理阶段的核心优化技术。在标准的自回归（autoregressive）解码中，模型逐 token 生成序列：给定已有的 <span class="math inline">\(N\)</span> 个 token，预测第 <span class="math inline">\(N+1\)</span> 个 token；然后将第 <span class="math inline">\(N+1\)</span> 个 token 拼接到输入中，继续预测第 <span class="math inline">\(N+2\)</span> 个 token，以此类推。这一机制的瓶颈在于——每一步都需要对整个序列重新计算注意力。</p>
<p>具体来说，在第 <span class="math inline">\(N\)</span> 步解码时，输入序列长度为 <span class="math inline">\(N\)</span>，注意力矩阵 <span class="math inline">\(QK^T\)</span> 的尺寸为 <span class="math inline">\(N \times N\)</span>，其计算量随 <span class="math inline">\(N\)</span> 线性增长，总解码 <span class="math inline">\(N\)</span> 个 token 的计算复杂度为 <span class="math inline">\(O(N^2)\)</span>。然而，观察 self-attention 的计算过程可以发现：对于已经计算过的历史 token，其键向量 <span class="math inline">\(K\)</span> 和值向量 <span class="math inline">\(V\)</span> 在后续步骤中<strong>完全不变</strong>——因为因果掩码（causal mask）确保当前 token 不会影响历史 token 的表示。唯一增加的只是当前新 token 的查询向量 <span class="math inline">\(Q_{\text{new}}\)</span> 与所有历史 <span class="math inline">\(K\)</span>、<span class="math inline">\(V\)</span> 之间的交互。</p>
<p>KV Cache 正是利用这一性质：在生成每个新 token 时，只计算新 token 的 <span class="math inline">\(Q\)</span>、<span class="math inline">\(K\)</span>、<span class="math inline">\(V\)</span>，将新 token 的 <span class="math inline">\(K\)</span>、<span class="math inline">\(V\)</span> 追加到缓存中，然后用新 token 的 <span class="math inline">\(Q\)</span> 与缓存中全部历史 <span class="math inline">\(K\)</span> 计算注意力分数，最终从缓存的 <span class="math inline">\(V\)</span> 中加权聚合。这样，每步解码的计算量从 <span class="math inline">\(O(N^2)\)</span> 降至 <span class="math inline">\(O(N)\)</span>，总解码复杂度从 <span class="math inline">\(O(N^2)\)</span> 降至 <span class="math inline">\(O(N^2)\)</span> 中的常数因子大幅减小（约减少一半乘法运算）。</p>
</section>
<section id="kv-cache-的实现" class="level4">
<h4 class="anchored" data-anchor-id="kv-cache-的实现">KV Cache 的实现</h4>
<p>基于 <a href="#sec-multi-head-attention">5.7</a> 节中的 <code>MultiHeadAttention</code>，我们在 <a href="flash_att/kv_cache_module.py">flash_att/kv_cache_module.py</a> 中实现了支持 KV Cache 的多头注意力模块 <code>MultiHeadAttentionKV</code>（继承自 <code>MultiHeadAttention</code>），以及配套的 <code>TransformerBlockKV</code> 和 <code>TransformerModuleKV</code>。</p>
<p><strong>MultiHeadAttentionKV 核心逻辑：</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MultiHeadAttentionKV(MultiHeadAttention):</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""MultiHeadAttention with KV cache support. Inherits all weights from parent."""</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x, token_positions<span class="op">=</span><span class="va">None</span>, past_kv<span class="op">=</span><span class="va">None</span>, use_cache<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>        batch_size, seq_len, _ <span class="op">=</span> x.size()</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 计算当前步的 Q, K, V</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>        Q <span class="op">=</span> <span class="va">self</span>.W_q(x).view(batch_size, seq_len, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>        K_cur <span class="op">=</span> <span class="va">self</span>.W_k(x).view(batch_size, seq_len, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>        V_cur <span class="op">=</span> <span class="va">self</span>.W_v(x).view(batch_size, seq_len, <span class="va">self</span>.n_heads, <span class="va">self</span>.head_dim).transpose(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> token_positions <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>            Q <span class="op">=</span> <span class="va">self</span>.rope(Q, token_positions)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>            K_cur <span class="op">=</span> <span class="va">self</span>.rope(K_cur, token_positions)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>        <span class="co"># 拼接历史 KV</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>        past_K <span class="op">=</span> past_V <span class="op">=</span> <span class="va">None</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> past_kv <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>            past_K, past_V <span class="op">=</span> past_kv</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> past_K <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>            K <span class="op">=</span> torch.cat([past_K, K_cur], dim<span class="op">=</span><span class="dv">2</span>)   <span class="co"># [B, H, past+cur, D]</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>            V <span class="op">=</span> torch.cat([past_V, V_cur], dim<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>            K, V <span class="op">=</span> K_cur, V_cur</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>        present_kv <span class="op">=</span> (K, V) <span class="cf">if</span> use_cache <span class="cf">else</span> <span class="va">None</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Attention 计算（优先使用 flash_attn 的 kvcache API）</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>        <span class="co"># ...</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> output, present_kv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>KV Cache 推理函数</strong>（<a href="basics/inference/inference_kv.py">basics/inference/inference_kv.py</a>）：</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> decode_token_kv(input_tokens, model_kv, max_tokens_to_generate, top_p<span class="op">=</span><span class="fl">0.9</span>, temperature<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    model_kv.<span class="bu">eval</span>()</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    input_tokens <span class="op">=</span> input_tokens.clone().detach().unsqueeze(<span class="dv">0</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    past_kvs <span class="op">=</span> <span class="va">None</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Prefill: 处理完整 prompt，建立 KV cache</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>        logits, past_kvs <span class="op">=</span> model_kv(input_tokens, past_kvs<span class="op">=</span>past_kvs, use_cache<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(max_tokens_to_generate):</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>            probabilities <span class="op">=</span> temperature_scaling(logits, temperature)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>            next_token_idx <span class="op">=</span> top_p_sampling(probabilities, top_p)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>            input_tokens <span class="op">=</span> torch.cat([input_tokens, next_token_idx], dim<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Decode: 仅将新 token 送入模型，复用缓存的 K/V</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>            logits, past_kvs <span class="op">=</span> model_kv(next_token_idx, past_kvs<span class="op">=</span>past_kvs, use_cache<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> input_tokens</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>与无 KV Cache 的推理函数对比：标准推理每步将整个（不断增长的）序列重新输入模型 → 注意力每步从头计算 <span class="math inline">\(O(N^2)\)</span>；而 KV Cache 推理在 Prefill 后将每步输入缩减为单个 token → 注意力仅算新 token 对缓存的查询 <span class="math inline">\(O(N)\)</span>。</p>
</section>
<section id="实验结果" class="level4">
<h4 class="anchored" data-anchor-id="实验结果">3. 实验结果</h4>
<p>为验证 KV Cache 的有效性，我们在 CPU 环境下设计了对照实验（代码见 <a href="kvcache实验/">kvcache实验/</a> 目录）。实验使用相同的模型检查点（80M 参数，8 层，8 头），对 4 种 prompt 长度（10、100、1000、10000 tokens）各测试 10 条相同 prompt，每条生成 2 个新 token。对比方法为：</p>
<ul>
<li><strong>无 KV Cache</strong>：每步将完整序列送入 <code>TransformerModule</code>，注意力从头计算</li>
<li><strong>有 KV Cache</strong>：Prefill 处理完整 prompt 后，每步仅送入 1 个新 token 至 <code>TransformerModuleKV</code></li>
</ul>
<p>两种方法固定相同的随机种子以确保可比性。<strong>加速比按 decode 阶段的 per-token 耗时计算</strong>，排除 prefill 的干扰，直接反映每步生成新 token 的加速效果。</p>
<p><strong>实验结果：</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Prompt 长度</th>
<th>Prefill 时间</th>
<th>无 KV Cache decode 均值</th>
<th>有 KV Cache decode 均值</th>
<th>加速比</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>10</strong></td>
<td>0.0222 ± 0.0019 s</td>
<td>0.0219 ± 0.0018 s/token</td>
<td>0.0172 ± 0.0020 s/token</td>
<td><strong>1.29 ×</strong></td>
</tr>
<tr class="even">
<td><strong>100</strong></td>
<td>0.0497 ± 0.0011 s</td>
<td>0.0508 ± 0.0020 s/token</td>
<td>0.0163 ± 0.0004 s/token</td>
<td><strong>3.13 ×</strong></td>
</tr>
<tr class="odd">
<td><strong>1000</strong></td>
<td>0.3759 ± 0.0042 s</td>
<td>0.3880 ± 0.0046 s/token</td>
<td>0.0199 ± 0.0014 s/token</td>
<td><strong>19.59 ×</strong></td>
</tr>
<tr class="even">
<td><strong>10000</strong></td>
<td>22.6064 ± 0.3626 s</td>
<td>22.8818 ± 0.3043 s/token</td>
<td>0.0508 ± 0.0040 s/token</td>
<td><strong>452.80 ×</strong></td>
</tr>
</tbody>
</table>
<p><strong>实验结果分析</strong></p>
<section id="prefill-阶段加速" class="level5">
<h5 class="anchored" data-anchor-id="prefill-阶段加速">Prefill 阶段加速</h5>
<p><strong>Prefill 时间组成</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 28%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>组件</th>
<th>操作</th>
<th>FLOPs</th>
<th>备注</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Embedding</td>
<td>查表 <span class="math inline">\(N \to [N, d]\)</span></td>
<td>—</td>
<td>可忽略</td>
</tr>
<tr class="even">
<td>QKVO 投影（<span class="math inline">\(n_{\text{layers}}\)</span> 层）</td>
<td><span class="math inline">\(4 \times\)</span> MatMul <span class="math inline">\([N,d]\times[d,d]\)</span></td>
<td><span class="math inline">\(8 n_{\text{layers}} N d^2\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>FFN（<span class="math inline">\(n_{\text{layers}}\)</span> 层）</td>
<td><span class="math inline">\(3 \times\)</span> MatMul <span class="math inline">\([N,d]\times[d,d_{\text{ff}}]\)</span></td>
<td><span class="math inline">\(6 n_{\text{layers}} N d d_{\text{ff}}\)</span></td>
<td></td>
</tr>
<tr class="even">
<td>Attention <span class="math inline">\(QK^T\)</span>（<span class="math inline">\(n_{\text{layers}}\)</span> 层）</td>
<td>MatMul <span class="math inline">\([N,d_{\text{head}}]\times[d_{\text{head}},N]\)</span></td>
<td><span class="math inline">\(2 n_{\text{layers}} N^2 d\)</span></td>
<td>平方项，长序列瓶颈</td>
</tr>
<tr class="odd">
<td>Attention <span class="math inline">\(\text{Score}\!\cdot\!V\)</span>（<span class="math inline">\(n_{\text{layers}}\)</span> 层）</td>
<td>MatMul <span class="math inline">\([N,N]\times[N,d_{\text{head}}]\)</span></td>
<td><span class="math inline">\(2 n_{\text{layers}} N^2 d\)</span></td>
<td>平方项，长序列瓶颈</td>
</tr>
<tr class="even">
<td>LM Head</td>
<td>MatMul <span class="math inline">\([N,d]\times[d,V]\)</span></td>
<td><span class="math inline">\(2 N d V\)</span></td>
<td>只执行一次</td>
</tr>
<tr class="odd">
<td>采样</td>
<td>Temperature + Top-P</td>
<td>—</td>
<td>可忽略</td>
</tr>
</tbody>
</table>
<p><strong>瓶颈分析</strong></p>
<p>从实验数据验证了时间组成随序列长度 N 的迁移规律——L=10 → 100 增长约 2.2 倍（GPU kernel launch overhead 主导），L=100 → 1000 增长约 7.6 倍（<span class="math inline">\(O(N)\)</span> 线性投影项主导），L=1000 → 10000 增长约 60 倍（接近平方关系，<span class="math inline">\(O(N^2)\)</span> 注意力项开始显著贡献）：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>序列长度</th>
<th>主导开销</th>
<th>瓶颈本质</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>短序列（N &lt; 100）</td>
<td>GPU kernel launch + 内存带宽</td>
<td>计算量小，硬件利用率低</td>
</tr>
<tr class="even">
<td>中等序列（100 ~ 2048）</td>
<td>线性投影 QKVO + FFN（<span class="math inline">\(O(N \cdot d d_{\text{ff}})\)</span>）</td>
<td>每层需做 7 次大矩阵乘法，计算密集</td>
</tr>
<tr class="odd">
<td>长序列（N &gt; 2048）</td>
<td>Attention <span class="math inline">\(QK^T\)</span> + Score<span class="math inline">\(\cdot V\)</span>（<span class="math inline">\(O(N^2 \cdot d)\)</span>）</td>
<td>注意力矩阵 <span class="math inline">\(N \times N\)</span> 的计算与存储随 N 平方增长</td>
</tr>
</tbody>
</table>
<p>在本实验的 80M 参数小模型（d=768, d_ff=2048, n_layers=8）中，交叉点约在 N ≈ 2048 附近。当 N = 10000 时，<span class="math inline">\(O(N^2)\)</span> 注意力项的计算量约占总 FLOPs 的 87%，成为绝对瓶颈，直接导致 Prefill 时间从 0.38s 飙升至 22.6s。所以加速 Prefill 的核心目标是削减 Attention 的 <span class="math inline">\(O(N^2)\)</span> 计算量，并提升大矩阵乘法的硬件利用率。</p>
<p><strong>Prefill 加速技术</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>方法</th>
<th>原理</th>
<th>论文</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FlashAttention / FA2</td>
<td>分块计算 + 在线 softmax，SRAM 内完成注意力。复杂度不变（仍 <span class="math inline">\(O(N^2 d)\)</span>），但 HBM 读写从 <span class="math inline">\(O(N^2)\)</span> 降至 <span class="math inline">\(O(N)\)</span>，显存从 <span class="math inline">\(O(N^2)\)</span> 降至 <span class="math inline">\(O(N)\)</span>，实际加速 2–4×</td>
<td>Dao et al., <em>FlashAttention</em>, NeurIPS 2022; Dao, <em>FlashAttention-2</em>, 2023</td>
</tr>
<tr class="even">
<td>稀疏 / 滑动窗口注意力</td>
<td>限制每个 token 只关注局部窗口（大小 <span class="math inline">\(w\)</span>）或稀疏模式（stride / global+local），复杂度从 <span class="math inline">\(O(N^2 d)\)</span> 降至 <span class="math inline">\(O(N w d)\)</span>，<span class="math inline">\(w \ll N\)</span>，如 Sliding Window 取 <span class="math inline">\(w = 4096\)</span></td>
<td>Beltagy et al., <em>Longformer</em>, 2020; Child et al., <em>Sparse Transformer</em>, NeurIPS 2019; Zaheer et al., <em>BigBird</em>, NeurIPS 2020</td>
</tr>
<tr class="odd">
<td>低精度量化（FP8 / INT8）</td>
<td>将激活/权重量化为 FP8 或 INT8，利用 GPU Tensor Core 提升吞吐量。FP8 相比 BF16 吞吐提升 2×，INT8 提升 4×；不改变复杂度，但降低单位运算开销</td>
<td>Micikevicius et al., <em>FP8 Formats for Deep Learning</em>, 2022; Dettmers et al., <em>LLM.int8()</em>, NeurIPS 2022</td>
</tr>
</tbody>
</table>
</section>
<section id="decode-阶段加速" class="level5">
<h5 class="anchored" data-anchor-id="decode-阶段加速">Decode 阶段加速</h5>
<p><strong>Decode 时间组成（有 KV Cache）</strong></p>
<p>在 KV Cache 模式下，Decode 阶段每步只处理一个新 token（<span class="math inline">\(N_{\text{new}} = 1\)</span>）：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>模块</th>
<th>操作</th>
<th>复杂度</th>
<th>计算量（FLOPs）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>QKVO 投影</td>
<td><span class="math inline">\(4 \times\)</span> MatMul <span class="math inline">\([1, d] \times [d, d]\)</span></td>
<td><span class="math inline">\(O(d^2)\)</span></td>
<td><span class="math inline">\(8 d^2\)</span></td>
</tr>
<tr class="even">
<td>FFN（gate + up + down）</td>
<td><span class="math inline">\(3 \times\)</span> MatMul <span class="math inline">\([1, d] \times [d, d_{\text{ff}}]\)</span></td>
<td><span class="math inline">\(O(d \cdot d_{\text{ff}})\)</span></td>
<td><span class="math inline">\(6 d d_{\text{ff}}\)</span></td>
</tr>
<tr class="odd">
<td>Attention <span class="math inline">\(QK^T\)</span></td>
<td>MatMul <span class="math inline">\([1, d_{\text{head}}] \times [d_{\text{head}}, N]\)</span></td>
<td><span class="math inline">\(O(N \cdot d)\)</span></td>
<td><span class="math inline">\(2 N d\)</span></td>
</tr>
<tr class="even">
<td>Attention <span class="math inline">\(\text{score} \cdot V\)</span></td>
<td>MatMul <span class="math inline">\([1, N] \times [N, d_{\text{head}}]\)</span></td>
<td><span class="math inline">\(O(N \cdot d)\)</span></td>
<td><span class="math inline">\(2 N d\)</span></td>
</tr>
</tbody>
</table>
<p><strong>瓶颈分析</strong></p>
<p>Decode 的核心问题不是计算量，而是<strong>内存带宽瓶颈</strong>。每生成一个 token：</p>
<ol type="1">
<li><strong>加载模型权重</strong>：80M 参数 × 2 bytes（bf16）= 约 160 MB，每步都需要完整遍历一次</li>
<li><strong>读取 KV Cache</strong>：<span class="math inline">\(2 \times n_{\text{layers}} \times n_{\text{heads}} \times N \times d_{\text{head}}\)</span> 个元素。当 N=10000 时，KV Cache 约 <span class="math inline">\(2 \times 8 \times 8 \times 10000 \times 96 \times 2\)</span> bytes ≈ 246 MB，且随 N 线性增长</li>
<li><strong>计算密度极低</strong>：每个参数每步仅参与一次乘加运算（arithmetic intensity ≈ 1-2 FLOPs/byte），远低于 GPU 的计算峰值（约 300+ FLOPs/byte 的硬件能力），Decode 完全受限于 HBM 带宽</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 43%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>因素</th>
<th>无 KV Cache Decode</th>
<th>有 KV Cache Decode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>每步计算量</td>
<td><span class="math inline">\(O(N \cdot d^2 + N^2 \cdot d)\)</span></td>
<td><span class="math inline">\(O(d^2 + N \cdot d)\)</span></td>
</tr>
<tr class="even">
<td>硬件瓶颈</td>
<td>计算受限（compute-bound）</td>
<td>内存带宽受限（memory-bound）</td>
</tr>
<tr class="odd">
<td>BLAS 效率</td>
<td>高（GEMM, <span class="math inline">\([N,d] \times [d,d]\)</span>）</td>
<td>低（GEMV, <span class="math inline">\([1,d] \times [d,d]\)</span>）</td>
</tr>
<tr class="even">
<td>每步加载模型权重</td>
<td>一次</td>
<td>一次（相同）</td>
</tr>
<tr class="odd">
<td>每步加载 KV Cache</td>
<td>无（重新计算）</td>
<td>全量历史 K/V</td>
</tr>
</tbody>
</table>
<p><strong>Decode 加速技术（经典论文）</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 31%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>技术</th>
<th>针对的瓶颈</th>
<th>核心思想</th>
<th>代表论文</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Multi-Query / Grouped-Query Attention</strong></td>
<td>KV Cache 体积</td>
<td>减少 K, V 的 head 数量，MQA 压缩 <span class="math inline">\(n_{\text{heads}}\)</span> 倍，GQA 压缩 <span class="math inline">\(n_{\text{heads}}/n_{\text{groups}}\)</span> 倍，直接减少 KV Cache 读取带宽需求</td>
<td>Shazeer, 2019; Ainslie et al., 2023</td>
</tr>
<tr class="even">
<td><strong>KV Cache 量化</strong></td>
<td>KV Cache 内存占用与带宽</td>
<td>将 FP16 K/V 量化为 INT4/INT8 甚至 INT2，以微小精度损失换取 4-8× 的 Cache 压缩比，降低内存访问压力</td>
<td>Sheng et al., 2023; Liu et al., 2024; Hooper et al., 2024</td>
</tr>
<tr class="odd">
<td><strong>PagedAttention (vLLM)</strong></td>
<td>KV Cache 显存碎片与利用率</td>
<td>借鉴操作系统分页机制，将 KV Cache 划分为固定大小的 Page，按需分配、动态回收，近消除碎片，提升 batch 推理吞吐</td>
<td>Kwon et al., 2023</td>
</tr>
<tr class="even">
<td><strong>Speculative Decoding</strong></td>
<td>Decode 串行依赖（每步 1 token）</td>
<td>用小草稿模型快速生成 k 个候选 token，再用大模型一次 forward 并行验证，接受匹配前缀，实现每步生成多 token 而不损质量</td>
<td>Leviathan et al., 2023; Chen et al., 2023</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="flashattention-2" class="level3">
<h3 class="anchored" data-anchor-id="flashattention-2">9.3 FlashAttention-2</h3>
<p>FlashAttention-2 是 FlashAttention 的改进版本，其核心思想是通过<strong>分块（Tiling）计算</strong>将注意力计算从高带宽内存（HBM）移至片上 SRAM 中完成，避免在 HBM 中物化完整的 <span class="math inline">\(N \times N\)</span> 注意力矩阵。标准注意力需将 <span class="math inline">\(QK^T\)</span> 的完整结果写回 HBM 再读回做 softmax，当序列长度 <span class="math inline">\(N\)</span> 较大时，这一读写带来的内存带宽瓶颈远超过计算本身。FlashAttention 通过在线 safe softmax 算法将 softmax 分解为可合并的分块统计量，使得每个块仅在 SRAM 中完成”读取→计算→写回”循环，核心优化点包括： (1) 减少 HBM 访问次数——将中间注意力矩阵留存在 SRAM；(2) 在线更新 softmax 归一化因子，无需全局同步；(3) 反向传播时通过重计算（recomputation）代替存储中间激活，将显存开销从 <span class="math inline">\(O(N^2)\)</span> 降为 <span class="math inline">\(O(N)\)</span>。</p>
<p>FlashAttention-2 在第一代基础上进一步优化：(1) 将外层循环从 batch/head 维度移至序列长度维度，提高 GPU 并行度；(2) 减少非矩阵乘法运算（non-matmul FLOPs）占比；(3) 优化 warp 间的工作划分以适配新的 GPU 架构。</p>
<p><strong>预期效果</strong>：相比标准注意力，训练和推理速度提升 2–4 倍，显存占用从 <span class="math inline">\(O(N^2)\)</span> 降至 <span class="math inline">\(O(N)\)</span>，使更长上下文窗口（如 32K、128K tokens）的训练在单 GPU 上变得可行。</p>
<p><strong>本模型实测结果（80M 参数，单 GPU）：</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>配置</th>
<th>训练时间</th>
<th>显存占用</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>标准注意力（无 FlashAttention）</td>
<td>约 6 小时</td>
<td>约 24 GB</td>
</tr>
<tr class="even">
<td>启用 FlashAttention-2</td>
<td>约 4 小时</td>
<td>约 18 GB</td>
</tr>
<tr class="odd">
<td><strong>改善幅度</strong></td>
<td><strong>-33%</strong></td>
<td><strong>-25%</strong></td>
</tr>
</tbody>
</table>
<p>由此可见，FlashAttention-2 在本项目小规模模型上依然带来了可观的加速与显存节省，验证了其减少 HBM 访问和中间激活存储的核心收益。</p>
</section>
</section>
<section id="建议" class="level2">
<h2 class="anchored" data-anchor-id="建议">10 建议</h2>
<section id="优先阅读代码而非训练实操" class="level3">
<h3 class="anchored" data-anchor-id="优先阅读代码而非训练实操">10.1 优先阅读代码而非训练实操</h3>
<p>如果你想要学习大模型的预训练，我们推荐你去看模型和训练部分的代码，而不是投入大量时间进行训练实操。</p>
<p>原因有三：其一，80M 的模型参数量太小，模型最终效果有限，生成质量与真正的大模型相去甚远；其二，80M 规模的预训练耗时并不短（本项目在单张 4090 上仍需约 6 小时），但换来的体验却非常有限；其三，也是最重要的一点——80M 大小的预训练<strong>无法让你体验到现代大模型训练过程中的各种优化技术和实际挑战</strong>。</p>
</section>
<section id="代码测试非常重要" class="level3">
<h3 class="anchored" data-anchor-id="代码测试非常重要">10.2 代码测试非常重要</h3>
<p>本项目中我们踩过两个印象深刻的 bug，都是因为缺少充分的单元测试导致的，浪费了大量训练时间：</p>
<p><strong>Bug 1：TransformerBlock 忘记继承 <code>nn.Module</code>。</strong> 在模型搭建部分，<code>transformer_block</code> 类忘记写 <code>(nn.Module)</code> 继承。这导致该类的所有 <code>nn.Parameter</code> 和子模块（RMSNorm、MultiHeadAttention、SwiGLU）无法被 PyTorch 的 <code>model.parameters()</code> 自动发现——这些参数在优化器中”不存在”，<strong>完全不参与训练</strong>。损失只能降到 5 左右就再也下不去了（正常的训练损失应当降到 3.5 左右），我们排查了很久才发现是继承缺失的问题。加上 <code>nn.Module</code> 继承后，损失立刻正常下降。</p>
<p><strong>Bug 2：Tokenizer 忘记加入特殊符号。</strong> 在 BPE 训练和编码阶段，我们忘记将 <code>&gt;</code> 等特殊符号加入数据预处理流程。结果是——模型训练完成后虽然能生成通顺的文本，但<strong>无法输出终止符号</strong>，只能靠我们手动设置的最大长度来截断生成。生成内容往往会一直絮叨下去，直到达到 <code>max_tokens</code> 上限。这个 bug 的修复只需要在编码数据时确保特殊 token 被正确加入词表和训练数据中，但因为没有在 tokenizer 层面写测试，直到推理阶段才发现问题.</p>
<p>这两个 bug 的教训是：<strong>每个模块写完之后一定要写测试</strong>。Tokenizer 的测试（编码-解码一致性、特殊 token 处理）、模型的测试（参数可训练性验证、前向-反向完整性检查、梯度流动检查）都应该在开始正式训练之前完成。花 30 分钟写测试，可能省下 6 小时的无效训练。</p>
</section>
<section id="一定要看数据集内容" class="level3">
<h3 class="anchored" data-anchor-id="一定要看数据集内容">10.3 一定要看数据集内容！！！</h3>
</section>
<section id="参数初始化对本实验影响不大" class="level3">
<h3 class="anchored" data-anchor-id="参数初始化对本实验影响不大">10.4 参数初始化对本实验影响不大</h3>
<p>我们在这个项目中对参数初始化做了详细的调研和自定义实现（见 <a href="#sec-param-init">5.1 节</a>），使用了截断正态分布、精心选择了 <span class="math inline">\(\sigma=0.02\)</span> 等参数。但实验结果表明：在本项目的规模（80M 参数、1 个 epoch、14.58 亿 token）下，<strong>参数初始化对最终训练结果几乎没有影响</strong>。</p>
<p>无论是 Xavier 初始化、He 初始化、还是我们的截断正态分布，只要初始化的方差不过大（不导致梯度爆炸）或过小（不导致梯度消失），模型都能在几百步内迅速调整到相近的损失水平。这是因为：</p>
<ul>
<li>80M 参数模型的优化空间相对简单，优化器（AdamW）能够在足够多的训练步数内补偿初始化的差异</li>
<li>14.58 亿 token 的训练量足以让模型”忘记”初始化的影响</li>
<li>Pre-Norm 架构本身就降低了对初始化的敏感度</li>
</ul>
<p>参数初始化真正变得关键是在<strong>更大规模模型</strong>（1B+ 参数）和<strong>更深网络</strong>（48+ 层）上，那时不当的初始化会导致训练前期梯度爆炸或梯度消失，直接导致训练失败。但对于本项目这种小规模实验，初始化的重要性被高估了——<strong>把时间花在检查数据和写测试上，性价比远高于调初始化参数</strong>.</p>
<p>数据集 数据量多少？ pertaring效果 知识储备 续写能力 损失函数 2以下</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/qsdong-bupt\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Qingsen Dong. Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".foldable-header").forEach(header => {
    header.addEventListener("click", () => {
      const block = header.closest(".foldable");
      if (block) block.classList.toggle("is-open");
    });
    header.setAttribute("tabindex", "0");
    header.addEventListener("keydown", e => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        header.click();
      }
    });
  });
});
</script>




</body></html>